### ISSUE TITLE
ETC - Etre mieux informé des choix réalisés à la pré-inscription

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1018]
ETC, il faudrait que je sois informé de l'impact du choix du département
- [ ] Ajout de précisions sur les centres du département choisi (maquette à intégrer)
- [ ] Ajout d'un message et d'une coche obligatoire confirmant la compréhension des impacts de mes choix (message à préciser)

**Comment by baudointran** [comment]
@Evbern 
Est-ce que c'est toujours d'actualité?

**Comment by Evbern** [comment]
Issue n'étant plus d'actualité avec le changement de dép.
