### ISSUE TITLE
ETC - Changer de département pdt la période des 30 J

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1024]
ETC, je me rends compte que le département que j'ai choisi à la pré-inscription n'est pas le bon. Je souhaite alors changer de département alors que je suis dans la période d'attente de 30 jours.
- [ ] Ajouter à tous les mails de confirmation d’inscription (ie. le mail après validation Aurige) un lien pour changer de département
- [ ] Ajouter à tous les mails de confirmation d'inscription (ie. le mail après validation) la mention "Ce mail vous sert de nouvelle référence."
- [ ] le candidat clique sur ce lien qui renvoie vers une page de type formulaire où il doit choisir son Département et ou le NEPH et le NOM sont déjà remplis et non modifiables
- [ ] le candidat choisit son nouveau département
- [ ] une coche et un message d'information sur les 30 j apparaît (comme à la pré-inscription + ajout de "Vous recevrez un mail qui servira de nouvelle référence"
- [ ] le candidat coche la case qui apparaît
- [ ] le candidat clique sur confirmer ou annule via le bouton X
- [ ] le candidat reçoit un nouveau mail de confirmation de changement de département et contenant la nouvelle date d'accès : changer le titre "Changement de département", changer la première partie "Votre changement de département a bien été pris en compte (nouveau département : _nom du nouveau département_), conserver la fin du mail de confirmation d'inscription (partie rétention)
- [ ] le changement de Département est historisé et ajouté à la fiche candidat

**Comment by baudointran** [comment]
Plus d'actualité
Il est remplacé par les issues #1043, #1044, #1045
