### ISSUE TITLE
 ETC - Changer de département après la période des 30 J

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1025]
ETC, je me rends compte que le département que j'ai choisi à la pré-inscription n'est pas le bon. Je souhaite alors changer de département alors que j'ai déjà accès au planning de réservation
- [ ] Processus identique à la #1024 
- [ ] Le candidat accès au formulaire depuis une page intégrée au site candilib via un bouton dédié dans le header

**Comment by baudointran** [comment]
Plus d'actualité
Il est remplacé par les issues #1043, #1044, #1045
