### ISSUE TITLE
ETC - Modifier libellé dans le formulaire de préinscirption

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1043]
ETC, je dois choisir via une liste déroulante dans le formulaire de pré-inscription 
- [x] Mon département de résidence

**Comment by baudointran** [comment]
API:
- [ ] Ajouter le département de résidence dans le model du candidat

**Comment by baudointran** [comment]
Voici la nouvel page
![image](https://user-images.githubusercontent.com/16351036/77560473-d767cd80-6ebd-11ea-8397-8774b05bf4bc.png)


Il n'y a plus de case à cocher et de texte explicatif du choix de département

**Comment by Evbern** [comment]
OK @baudointran  ! Top
