### ISSUE TITLE
Nouveau wording de mail pour une réussite 

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1047]
Nouveau courriel pour les candidats qui ont réussit l'examen:

Selon nos informations, vous avez réussi l'examen que vous venez de passer. 
Votre certificat d'examen sera disponible sous 24 heures (hors week-end et jours fériés) ici :
Résultatspermisdeconduire.gouv.fr
Attention : seul le certificat téléchargé sur ce site établira officiellement votre réussite et vous autorisera la conduite.

Ce mail est purement informatif et n'engage en rien l'administration sur votre résultat définitif.

**Comment by baudointran** [comment]
@Evbern 
Est-ce que le lien Résultatspermisdeconduire.gouv.fr existe?
Résultatspermisdeconduire.gouv.fr est introuvable

**Comment by baudointran** [comment]
https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire#/step-connexion

**Comment by Evbern** [comment]
OK @baudointran , vu avec Fred, go pour utiliser le lien suivant : 
https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire#/step-connexion

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/76983902-6b75ea00-693e-11ea-8e24-e6bc9f08965d.png)

**Comment by baudointran** [comment]
Ce mail est envoyé dans le cas où le candidat est un candidat inscrit et qui ont réussi l'examen pratique par Candilib ou par un auto-école.
Le précédent de "Information Candilib" est envoyé pour les candidats pré-inscrit qui ont l'examen

**Comment by baudointran** [comment]
Voici la correction dans le corps du mail

![image](https://user-images.githubusercontent.com/16351036/77170050-c2a0c980-6aba-11ea-922e-13bd26a0ba76.png)
