### ISSUE TITLE
Mail dans le cas d'un non examiné

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1050]
Vous n'avez pas été examiné car vous ne remplissiez pas toutes les conditions réglementaires obligatoires pour tout candidat.
Nous avons perdu une place qui aurait pu bénéficier à un autre candidat.
Vous conservez votre accès à Candilib, mais il vous est appliqué une pénalité de 45 jours de délais avant de pouvoir effectuer une nouvelle réservation.

**Comment by baudointran** [comment]
Je propose comme le sujet: 'Information Candilib'
le corps du mail ci-dessous:

<p>Madame, Monsieur TEST,</p>
<br>
<p>
Vous n'avez pas été examiné car vous ne remplissiez pas toutes les conditions réglementaires obligatoires pour tout candidat.
  <br> Nous avons perdu une place qui aurait pu bénéficier à un autre candidat.
</p>
<p>
Vous conserverez votre accès à Candilib, mais il vous sera appliqué une pénalité de 45 jours de délais avant de pouvoir effectuer <a href="lien candilib pour réserver">une nouvelle réservation</a>.
</p>
<p>
Pour toute information, vous pouvez consulter <a href="lien vers la FAQ">notre aide en ligne</a>.
<br>Vous pouvez nous contacter à cette adresse <a href="mailto:${departementInfo.email}">${departementInfo.email}</a> 
</p>
<br>
<p align="right">L'équipe Candilib</p>

**Comment by Evbern** [comment]
Je propose comme le sujet: 'Information Candilib'
le corps du mail ci-dessous:

<p>Madame, Monsieur TEST,</p>
<br>
<p>
Vous n'avez pas été examiné car vous ne remplissiez pas toutes les conditions réglementaires obligatoires pour tout candidat.
  <br> Nous avons perdu une place qui aurait pu bénéficier à un autre candidat.
</p>
<p>
Vous conserverez votre accès à Candilib, mais il vous sera appliqué une pénalité de 45 jours de délais avant de pouvoir effectuer <a href="lien candilib pour réserver">une nouvelle réservation</a>.
</p>
<p>
Pour toute information, vous pouvez consulter <a href="lien vers la FAQ">notre aide en ligne</a>.
<br>Vous pouvez nous contacter à cette adresse <a href="mailto:${departementInfo.email}">${departementInfo.email}</a> 
</p>
<br>
<p align="right">L'équipe Candilib</p>

**Comment by baudointran** [comment]
@Evbern 
Qui sont les candidats non examinés? Est-ce que sont les autres ( non-examinbale, annulé, non recevable) ou juste les non examinables

**Comment by Evbern** [comment]
@baudointran je confirme (vu avec Fred) que les non examinés = non examinables, non recevables, annulés (dans Aurige)

**Comment by baudointran** [comment]
- [ ] Mail est envoyé que dans le cas où le candidat a échoué et a réservé une place
