### ISSUE TITLE
ETC - Etre informé de la fermeture du service Candilib

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1054]
ETC, je suis informé de la fermeture provisoire du service

- [x] Création d'une page simple informant de la fermeture du service 
- [x] Contenu du message :

"En raison de la situation de crise pandémique liée au coronavirus COVID 19, les examens du permis de conduire sont suspendus jusqu'à nouvel ordre. Le site candilib restera indisponible durant cette période. Toutes les informations sur www.securite-routiere.gouv.fr

Ne vous déplacez pas. 
Toutes les informations sur www.gouvernement.fr"

**Comment by baudointran** [comment]
En raison de la situation de crise pandémique liée au coronavirus COVID 19, les examens du permis de conduire sont suspendus jusqu'à nouvel ordre. Le site candilib est momentanément indisponible.
En cas d'annulation de votre examen vous recevrez un courriel vous en informant.
Vous présentant nos excuses pour la gêne occasionnée.
