### ISSUE TITLE
Ajouter departement géographique pour les centres

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1064]
Associé à 1044

**Comment by baudointran** [comment]
@Evbern 
Voici ma proposition pour l'ajout du département géographique pour lors la gestion des centres 
![image](https://user-images.githubusercontent.com/16351036/78111056-62841e80-73fc-11ea-8a7b-5aff64ea4814.png)

**Comment by Evbern** [comment]
Ok pour moi Baudoin !

**Comment by baudointran** [comment]
proposition 1, pour la liste des centres
![image](https://user-images.githubusercontent.com/16351036/78144680-34203680-7430-11ea-8476-7beb9b3071b2.png)

**Comment by baudointran** [comment]
proposition 2: 
![image](https://user-images.githubusercontent.com/16351036/78144728-469a7000-7430-11ea-8af2-f4ff4b185b5f.png)

**Comment by baudointran** [comment]
Laquelle des 2 propositions est le plus compréhensible pour faire la différence entre le département administratif et géographique?

**Comment by Evbern** [comment]
@baudointran je dirais ta proposition 3 du slack :). Merci !

![image](https://user-images.githubusercontent.com/48919541/78147893-6af84b80-7434-11ea-9091-cff0bad20c9a.png)

**Comment by baudointran** [comment]
@Evbern  Peux-tu tester la version présent dans la qualif est de me faire un retour?

**Comment by Evbern** [comment]
@baudointran c'est OK pour moi.
Pour plus tard, il faudra voir s'il y n'y a pas un interet à modifier le département administratif, car on ne peut pas pour l'instant.
