### ISSUE TITLE
ETC: Page Choix de centre, affichage par departement geolocalisé 

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#1069]
- [ ] numérotation des doublons de centres
link #1044

**Comment by baudointran** [comment]
API:
- [ ] Requête nombre de place par centre par département géographique

**Comment by jclaudan** [comment]
voir avec @laruiss : le département administratif ne doit plus apparaître cependant, il nous le faut pour identifier le centre selectionné lorsque le candidat ré-actualise la page de confirmation de reservation,

**Comment by jclaudan** [comment]
ne pas encoyer le depatement administratif au front, et l'Id du centre sera mis dans le localStorage vue @baudointran  @laruiss
