### ISSUE TITLE
Dans le mail de réussite et d'echec mettre 48h au lieu de 24h

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1075]
@Evbern 
Peux-tu me confirmer qui faut changer dans les mails de réussite et d'échec de remplacer 24h par **48h** ?

Associée à #1047 et #1048

**Comment by Evbern** [comment]
@baudointran OK pour mettre 48h (vu avec Fred)

**Comment by baudointran** [comment]
@Evbern Corrigé, peux-tu vérifier et validé?

**Comment by Evbern** [comment]
@baudointran C'est testé et OK pour moi !
