### ISSUE TITLE
ETC - Formulaire : e-mail de confirmation

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1089]
ETC, je souhaite contacter l'administration relativement à Candilib.

Après avoir envoyé ma demande, je suis informé de l'envoi, comme suit.

**Je reçois un mail de confirmation** 
- [x]  Titre : "Prise en compte de votre demande"
- [x] De : ne-pas-répondre
- [x] Corps :
>"Madame, Monsieur,
Votre demande a bien été transmise aux services de votre département déclaré. L'administration vous répondra dans les plus brefs délais.
Sans réponse de notre part au bout d'une semaine, nous vous invitons à réitérer votre demande.
L'équipe Candilib."

**Comment by baudointran** [comment]
<p>Madame, Monsieur,</p>
  <p>
Votre demande a bien été transmise aux services de votre département déclaré. <br>
L'administration vous répondra dans les plus brefs délais. <br>
Sans réponse de notre part au bout d'une semaine, nous vous invitons à réitérer votre demande.</p>
<br/>
<p align="right">L'équipe Candilib</p>

**Comment by baudointran** [comment]
Pour un candidat résilient au 75 et sa réservation est au 93

Pour un candidat non inscrit:

<p>Madame, Monsieur,</p>
  <p>
Votre demande a bien été transmise aux services de votre département 93. <br>
L'administration vous répondra dans les plus brefs délais. <br>
Sans réponse de notre part au bout d'une semaine, nous vous invitons à réitérer votre demande.</p>
<br/>
<p align="right">L'équipe Candilib</p>
