### ISSUE TITLE
ETC - Renvoyer vers le formulaire de contact depuis les mails

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1096]
ETC, je souhaite pouvoir être redirigé vers le formulaire de contact dans les mails suivants 
- [x] Mail annulation
- [x] Mail convocation
- [x] Autres mails pour lesquels le lien "Nous contacter" est déjà présent

**Comment by baudointran** [comment]
Proposition TECH:

Le lien "Nous contacter" contient un token de connexion comme le magic link avec une redirection vers le formulaire

si le candidat n'a pas le droit se connecter, il y aura que le lien vers le page

**Comment by Evbern** [comment]
Ok @baudointran
