### ISSUE TITLE
ETC - Mettre à jour la FAQ pour le changement de déparement

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1098]
```
Comment ça marche ?

Pour s'inscrire

Rendez-vous sur la page d'accueil du service pour se pré-inscrire.

Vous saisirez sur le formulaire vos NEPH (le numéro que vous avez reçu pour l'inscription au permis), nom de naissance, prénom, mail, téléphone et département de passage.

Vous devez dès à présent choisir votre département de passage à l'examen. Votre choix permet à l'administration de provisionner un nombre de places d'examen suffisant pour chaque département où Candilib est disponible
```
- [ ] Remplacer le département de passage par mon département de résidense

```
Pour réserver

Connectez-vous à Candilib après réception du mail « Validation de votre inscription à Candilib » (lien de connexion dans le mail de validation).

Sélectionnez votre centre d'examen, puis un créneau disponible à la date qui vous convient (si besoin, déplacez-vous sur les vues « mois », « semaine » et « jour »).

Confirmez votre réservation.
```
- [ ] Ajouter 'Sélectionnez votre département de passage, puis ' 

à groomer

**Comment by Evbern** [comment]
@baudointran je crois que c'est déjà prévu dans la #1088. Tu confirmes que tu parles de la même chose ?

**Comment by Evbern** [comment]
**Qui peut utiliser le service ?**
- Ajouter "actuellement" avant "des places via ce service"
- Ajouter la liste des départements utilisant Candilib
- Supprimer le département 75
- Supprimer le paragraphe NB

**Comment ça marche - Pour s'inscrire**
- Remplacer "passage" par "résidence"
- Ajouter ensuite le paragraphe suivant : 
- Supprimer le paragraphe "Vous devez ..."
