### ISSUE TITLE
Format du mail de contact recu par la BER

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1099]
ETR, je reçois la demande du candidat par le formulaire de contact. la demande est contient tous les informations saisi par le candidat.

```
Titre : Objet de la demande saisi par le candidat
De : ne-pas-répondre
Corps :
Information Candidat
NEPH : code saisi par le candidat
Nom: nom saisi par le candidat
adresse courriel: emailto: <e-mail saisi par le candidat> (avec le Objet de la demande si possible)
Candidat pré-inscrit ou inscrit: oui ou non
message:
 message du candidat
```

**Comment by Evbern** [comment]
Top @baudointran

**Comment by baudointran** [comment]
<p>
<strong>Infromation Candidat:</strong><br>
<ul>
<li>  NEPH: codeNeph</li>
  <li>  Nom: nomNaissance</li>
  <li>  Prénom: prenom</li>
  <li>  Courriel: <a href="mailto:mail?subject=Subject" >email</a></li>
  <li>  Portable: 0612345678</li>
  <li>  Département: 93</li>
  <li>  Candidat pré-inscrit ou inscrit: oui</li>
</ul>
</p>
<p>
<strong>Message: </strong>

teststsjml
</p>
