### ISSUE TITLE
ETC - Renommer le label de la page pré-inscription

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1102]
ETC, lorsque je réalise ma pré-inscription via le formulaire.

Il convient d'apporter les ajustements suivants

- [x] Ajouter la mention suivante "Si votre département de résidence n'apparaît pas, vous pouvez néanmoins sélectionner un autre département pour y passer l'examen" en dessous du champ dédié dans une police plus petite que celle du label

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/79753166-c6bc4300-8315-11ea-9030-fab279f105ee.png)

**Comment by Evbern** [comment]
Top !
