### ISSUE TITLE
ETC - Mettre à jour la FAQ (suite)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1103]
Il convient d'ajouter une sous-section dans la section "Comment ça marche" 

**Comment ça marche - Je n’ai pas reçu la validation de ma pré-inscription après 48 h** 
- [x] Un problème technique peut avoir empêché la vérification de votre pré-inscription. Si vous n’avez pas reçu de mail de validation ou de rejet après 4 jours (hors week-ends et jours fériés), vous pourrez contacter votre service Candilib

Il convient d'ajouter une section "Où trouver mon résultat d'examen ?" avec les sous-sections suivantes 

**Où trouver mon résultat d'examen - Où Consulter mon résultat ?**
- [x] Vous pouvez accéder à votre résultat d'examen en consultant le lien suivant : https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire

**Où trouver mon résultat d'examen - Je n’ai pas accès à mon résultat d'examen** 
- [x] Candilib me fait savoir que j’aurais réussi mon examen mais je ne vois pas le résultat sur le site de la Sécurité Routière. Les résultats sont généralement en ligne sous 72 h (hors week-ends et jours fériés) mais il y a pu y avoir un problème de remontée informatique. 

**Où trouver mon résultat d'examen - Je vois mon ancien résultat d'examen**
- [x] Votre ancien résultat d'examen apparaît sur le site de la Sécurité Routière. Les résultats sont généralement en ligne sous 72 h (hors week-ends et jours fériés) mais il y a pu y avoir un problème de remontée informatique. D'autre part, entre 2 visites sur le site, vous devez quitter votre navigateur et vous reconnecter, le simple "rafraîchissement" de la page ne permettant pas de provoquer un nouvel affichage des résultats.

Dans la section "Je ne trouve pas de place disponible ?", il convient de 
- [x] Supprimer la mention : "D'autres peuvent se libérer à tout moment par l'annulation d'un candidat ayant réservé."

**Comment by baudointran** [comment]
@BCARPANO-nov 
Je pense qui est mieux que :
- 'Contacter votre service Candilib' soit un lien qui point vers contact-us de candilib
- 'le site de la Sécurité Routière' soit un lien qui point vers https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire

**Comment by BCARPANO-nov** [comment]
Salut @baudointran 
On parle bien de la sous-section "Où trouver mon résultat d'examen - Où Consulter mon résultat ?" ?
Le contact au service Candilib "contact-us" représente bien le lien vers le formulaire de contact Candilib ?
J'aurais tendance à ne laisser que 'le site de la Sécurité Routière' soit un lien qui pointe vers https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire
Je pense que l'objectif est que le candidat aille directement consulter son résultat sur le site sans solliciter le BER via le formulaire de contact, pour justement diminuer les demandes sur ce point qui arrivaient jusqu'au BER.
A ta dispo si questions

**Comment by baudointran** [comment]
Le contact au service Candilib "contact-us" représente bien le lien vers le formulaire de contact Candilib ?
oui
