### ISSUE TITLE
ETR - Gérer le planning, pour les places libérées jusqu’à J + 7

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#1110]
Sur la page Candilib de gestion du planning, pour les places libérées jusqu’à J + 7, faire apparaître en grisé (ou autre moyen de distinction) les références du candidat (minimum NEPH) qui avait pris la réservation (y compris si action admin). Cette fonction nous permettra de visualiser qui a annulé la place au dernier moment.

attendre la reouverture candilib afin de confirmer cette issues

**Comment by baudointran** [comment]
N'est-il pas plus simple d'interdire l’affectation d'un candidat qui à une réservation dans un autre département administrative?
