### ISSUE TITLE
ETC - Note d'information sur les centres du 75 pour le candidat 75 connecté

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1175]
En tant que candidat ayant déclaré une adresse de résidence dans le 75, lorsque je choisis mon département pour passer l'examen, un bandeau s'affiche

- _NB de la FAQ_
- Pour les centres suivants _liste des centres utilisés uniquement par le 75_, vous pouvez contacter le service Candilib 75 en cas de problème

**Comment by baudointran** [comment]
Resultat:
![image](https://user-images.githubusercontent.com/16351036/84748100-78938b00-afb8-11ea-8615-2e6576add63e.png)

**Comment by baudointran** [comment]
Nouveau texte: 
"Les centres utilisés par le département 75 sont localisés hors 75 et sont les suivants : liste des centres du 75
Pour les centres suivants liste des centres exclusivement 75, veuillez contacter le service Candilib 75 en cas de problème"

**Comment by Evbern** [comment]
ok
