### ISSUE TITLE
Dans le mail de reussite au permis d'un canddiat avant la validation de l'inscription 

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1182]
Remplace la partie 
"Attention :
 Si vous recevez ce message et que vous êtes en situation de retour au
 permis de conduire après une annulation de votre permis, vous ne pouvez pas vous
 pré-inscrire sur le site Candilib. Nous vous invitons à prendre contact
 avec le service Candilib en indiquant votre situation : lien
 formulaire."

**Comment by Evbern** [comment]
@baudointran pourrais-tu m'indiquer comment tester ce cas stp ? Je ne pense pas avoir le cas dans le json. Merci

**Comment by Evbern** [comment]
Mais le texte dans l'issue est OK ;)

**Comment by baudointran** [comment]
@Evbern c'est le cas du candidat test.success@test.com

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/84743733-a70e6780-afb2-11ea-94b1-b8161094b0c8.png)

**Comment by Evbern** [comment]
Ok top merci. J'avais trop vite lu le mail dans mailtrap. C'est good !
