### ISSUE TITLE
ETC, quand je rafraichie la page des choix de places, je dois avoir le nom de centre choisi et la liste des places

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1189]
Observation TECH:
Aprés un rafraichissement de la page, une demande continue de récupération de places  tous les milliseconde à l'API

![image](https://user-images.githubusercontent.com/16351036/85154460-c4b02b00-b257-11ea-9faa-bb86d671b79a.png)

**Comment by Evbern** [comment]
ok
