### ISSUE TITLE
Enregistrer une réservation

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#119]
Associé à #79 

Entrypoint 'api/v2/candidat/reservations'

parametres: 
- id: id centre
- date: date de place
- isAccompanied
- hasDualControlCar

**Comment by baudointran** [comment]
Fonctionnalité: 
 - [ ] Annulation de la réservation précédente
 - [ ] Enregistrement de d'une réservation 
 - [ ] Envoi de mail pour la réservation
 - [ ] Envoi de mail pour la modification
 - [ ] Archivage de réservation ?

**Comment by laruiss** [comment]
Fait
