### ISSUE TITLE
ETC - Être informé de la publication des places à 12h dans le funnel de réservation

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1198]
ETC, je souhaite être informé des régles de publication de places dans le funnel de réservation de place :
- [ ] Ajout du texte suivant "Si de nouveaux créneaux sont ajoutés, ils seront mis en ligne tous les midis" de manière permanente en police gris foncé, dans le funnel de réservation de places du candidat, au dessou de "CHOIX DU DEPARTEMENT" pour l'étape 1, de "CHOIX DU CENTRE" pour l'étape 2, du nom du centre d'examen pour l'étape 3

![image](https://user-images.githubusercontent.com/48919541/85736816-1ac11a80-b6ff-11ea-890e-b66504f512dd.png)

**Comment by baudointran** [comment]
- [ ] Présent dans le choix de departements
- [ ] Présent dans le choix de centres
- [ ] Présent dans le choix de places

**Comment by Evbern** [comment]
ok
