### ISSUE TITLE
ETR - Modifier l'adresse e-mail candidat

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#1220]
ETR, je dois pouvoir modifier l'adresse e-mail du candidat afin de lui permettre d'avoir accès au service, lorsqu'il n'a plus accès ou n'utilise plus l'adresse e-mail initialement déclarée.
- [ ] Sur la fiche candidat, afficher l'adresse e-mail du candidat
- [ ] Ce champ doit être modifiable
- [ ] Un contrôle sur le format du mail doit être effectué (ex : comme lors de l'inscription)
- [ ] Le candidat ne souffre d'aucune pénalité associée à la modification de son adresse e-mail
- [ ] Cette modification entraîne l'envoi d'un mail (sur son ancienne et sa nouvelle adresse, par sécurité) informant le candidat de la modification de son e-mail #1224 

_Métier : il est conseillé de n'effectuer la modification qu'en cas de blocage pour ne pas systématiser la pratique_

**Comment by baudointran** [comment]
Tech:
- [ ] Archiver l'ancien e-mail, la date de modification et qui fait la modification

**Comment by baudointran** [comment]
@Evbern 
N'est-il pas pus prudent d'avoir une message confirmation pour le répartiteur avant le modification?

**Comment by Evbern** [comment]
@baudointran 
Complètement d'accord avec toi. On peut rajouter cette étape, OK !

**Comment by Evbern** [comment]
OK.

Néanmoins, petite amélioration à apporter : lorsque je saisis une adresse mail qui est déjà utilisée par ailleurs, il m'est impossible de valider la modification (c'est normal) mais le message est en anglais (cf. screenshot). Il faudrait le remplacer par. "Cette adresse email est déjà utilisée par un autre utilisateur. Veuillez saisir une autre adresse email."
![Capture d’écran 2020-07-30 à 20 02 28](https://user-images.githubusercontent.com/48919541/88957993-1c52a500-d2a0-11ea-9de8-cc87a87f9330.png)

**Comment by Evbern** [comment]
@BCARPANO-nov pour info
