### ISSUE TITLE
Erreurs 502 lors du "rush" à midi

### ISSUE THREAD

**Issue by MickaelBergem** [LAB-MI/candilibV2#1226]
Je suis candidat (et développeur), et j'ai constaté que le serveur renvoyait un nombre significatif d'erreurs 502 lors du "rush" à midi lorsque les nouvelles places sont mises à disposition. Elles partent en quelques minutes, et pendant ce laps de temps, beaucoup d'erreurs se produisent, notamment des erreurs 502 renvoyées par le serveur.

Je n'ai pas noté précisément quelles URLs avaient retourné ce code, mais j'imagine que vous devriez pouvoir y accéder facilement si vous avez accès aux logs du reverse-proxy.

**Comment by pli01** [comment]
Bonjour @MickaelBergem ,

Merci pour votre contribution.
Nous investiguons actuellement cette perturbation apparue depuis la mise en ligne de cette nouvelle fonctionnalité semaine dernière.
Nous vous tiendrons informés.
Toutes nos excuses pour le désagrément.

**Comment by MickaelBergem** [comment]
Pas sûr que ça vous soit très utile, mais au cas où : j'utilise [HowFast Monitoring](https://www.howfast.tech/) pour suivre la performance de mes serveurs, et j'en profite aussi pour suivre Candilib. On voit sur le graphe du bas que le temps de réponse augmente au moment du rush à cause :

1. de la terminaison TLS (le serveur hébergeant **nginx** est dans les choux j'imagine)
2. de l'application elle-même (phase "wait", soit le serveur hébergeant l'app est aussi dans les choux, soit les connexions que l'API essaie de faire deviennent lentes : base de données, autres APIs, etc)

![image](https://user-images.githubusercontent.com/3510190/87775794-f6042280-c826-11ea-909f-b80fb281f04d.png)

**Comment by MickaelBergem** [comment]
Coucou @pli01, il semblerait que l'API soit complètement tombée (depuis ce matin 4h), https://beta.interieur.gouv.fr/candilib/api/v2/auth/candidat/verify-token?token=xxxx renvoie une 502, tout comme https://beta.interieur.gouv.fr/candilib/api/v2/candidat/config 

![HowFast Monitoring](https://user-images.githubusercontent.com/3510190/89897738-ce169d80-dbdf-11ea-8628-3431b6ded8fe.png)

**Comment by jclaudan** [comment]
Bonjour Mickael Bergem, merci de votre retour nous somme sur le coup :+1:

**Comment by baudointran** [comment]
Il doit plus avoir de retour 502
