### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by bzg** [LAB-MI/candilibV2#1255]
Bonjour, la [politique de contribution open source de l'Etat](https://www.numerique.gouv.fr/publications/politique-logiciel-libre/) recommande fortement l'usage d'une licence logicielle, parmi [celles-ci](https://www.data.gouv.fr/fr/licences).

Si je peux vous aider, n'hésitez pas à me contacter ou à en discuter dans cette issue.

**Comment by bzg** [comment]
Bonjour, je me permets de faire remonter cette issue dans les notifications. Comment vous aider ?

**Comment by liberforce** [comment]
Je confirme qu'il ne suffit pas de mettre son code sur github pour le rendre libre... Le code en l'état est propriétaire.
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
