### ISSUE TITLE
Impossible d'accéder à la page suivante après sélection d'un horaire

### ISSUE THREAD

**Issue by nicolasm277** [LAB-MI/candilibV2#1268]
Bonjour, j'ai beaucoup de problèmes pour accéder à Candilib, le site est toujours complètement saturé à midi à l'heure de publication des places. J'ai compris qu'il faut se connecter 5 mn avant et se positionner sur le département qui nous intéresse et attendre que les places soient publiées. Le problème maintenant c'est quand les jours avec les créneaux horaires sont publiés, il est impossible de valider la sélection d'un créneau horaire : je clique sur l'heure choisie mais rien ne se passe, ça tourne en rond et au bout d'un certain je reçois un message "place non disponible", que faut-il faire ? J'utilise mon téléphone pour accéder à l'application, est-ce que vous me conseillez d'utiliser un ordinateur et un navigateur précis : Firefox, Edge, IE ? Pouvez-vous m'aider à trouver une solution à ce problème cela fait plus de 2 mois que j'essaie de réserver un créneau. Merci d'avance. Nicolas

**Comment by laruiss** [comment]
Bonjour @nicolasm277,

Il existe effectivement un bug qui sera corrigé cette semaine qui fait que vous voyez un certain nombre de places qui ne sont en fait pas disponibles (elles sont prises par des candidats... qui ne peuvent pas les voir, il s'agit du même bug).

Ce bug ne peut apparaître que si on utilise l'API directement (ce que font certains bots), et qu'on ne passe pas par l'application web.

**Comment by nicolasm277** [comment]
Bonjour

Merci pour votre réponse j’attends donc la correction du bug sachant que je
n’utilise pas d’API et que je passe seulement par l’applocation web.
J’espère qu’après correction du bug je pourrais enfin réserver un créneau
cela fait 3 mois que j’essaie tous les midis sans y arriver !

Nicolas Meuric

**Comment by Ismailmezrani** [comment]
Bonjour, @laruiss 

Même problème ici 🖐️ ,

Vous allez faire quelque chose pour les bots ? Car nous sommes incapables de prendre un rendez-vous depuis la reprise après le confinement. 

Merci d'avance

**Comment by baudointran** [comment]
Corriger dans la version v2.9.5-beta7
