### ISSUE TITLE
Client: l'url de l api endpoint doit etre parametrable: /api/v2 (dev) ou /candilib/api/v2 (prod) 

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#127]
En mode prod: le client pointe vers /api/v2 hors l'url doit être /candilib/api/v2.

Dans le client, l'url du endpoint API doit etre parametrable. Hors PUBLIC_URL lors du build du client n'est pas pris en compte.

* en dev: /api/v2
* en prod /candilib/api/v2 (ou autre prefix)
Un fix possible est de remplacer PUBLIC_URL par BASE_URL

**Comment by pli01** [comment]
#128

**Comment by laruiss** [comment]
Fixé dans #128
