### ISSUE TITLE
Erreur de redirection

### ISSUE THREAD

**Issue by PaulLerner** [LAB-MI/candilibV2#1278]
Bonjour, 
J'ai envoyé le même message via le formulaire de contact mais j'ai probablement plus de chance ici :

Je suis dans l'incapacité de réserver une place sur le site candilib après plusieurs essais différents jours avec différents supports (smartphone ou ordinateur, Windows ou Ubuntu, Firefox ou Chrome).

Le site est systématiquement saturé à midi et ne fonctionne plus du tout, je vous rapporte différents problèmes :
- page blanche lorsque l'on clique sur le choix du centre ou du créneau (ni les centres ni les créneaux ne chargent même si l'on attend jusqu'à une minute avec une bonne connexion internet)
- on est redirigé vers le mauvais centre, par exemple si je clique sur 94 puis sur retour puis sur 78, je suis à nouveau redirigé vers 94. Des fois il suffit d'appuyer à nouveau sur retour pour que ça fonctionne correctement mais d'autres fois malgré une dizaine d'essais je suis bloqué sur 94 (par exemple).

Voici un message d'erreur qui s'affiche dans la console de mon navigateur si ça peut vous aider  :
```
Uncaught (in promise) Error: Redirected when going from "/candidat/home" to "/qu-est-ce-que-candilib" via a navigation guard.
    Xt chunk-vendors.fd501a4d.js:20
    Gt chunk-vendors.fd501a4d.js:20
    m chunk-vendors.fd501a4d.js:20
    e router-checks.js:89
    w chunk-vendors.fd501a4d.js:20
    _ chunk-vendors.fd501a4d.js:20
    e chunk-vendors.fd501a4d.js:20
    i chunk-vendors.fd501a4d.js:26
    o chunk-vendors.fd501a4d.js:26
chunk-vendors.fd501a4d.js:20:18047
```

Bien cordialement,

**Comment by laruiss** [comment]
Bonjour @PaulLerner, et merci pour votre message.

Nous savons que l'application subit tellement de lenteurs lors du rush de midi qu'elle en devient inutilisable. Cet état de fait ne dépend malheureusement pas uniquement de l'équipe de développement. Cela fait de nombreuses semaines que nous travaillons sur les améliorations, malheureusement avec les contraintes que nous avons, cela ne va pas aussi vite que nous le voudrions.

Pour ce qui ne relève pas de l'équipe de développement, nous restons dans l'attente de réponses et d'actions d'autres équipes.

En ce qui concerne l'erreur que vous avez signalé, nous vous en remercions. Elle sera corrigée très prochainement, cependant, elle n'a aucune incidence pour les utilisateurs.

À bientôt
