### ISSUE TITLE
Limitations - Appels des API's par des bots

### ISSUE THREAD

**Issue by scesardev** [LAB-MI/candilibV2#1295]
Il est de fait que plusieurs bots circulent et proposent des services payants afin de notifier ou de réserver automatiquement des places via des bots.

Il serait possible d'endiguer ces appels illégitimes en ajoutant une couche de sécurité/blocage qui évite à la même IP d'effectuer une requête plus d'une fois toute les X secondes.

Aujourd'hui quand on est sur la page d'un centre d'examen il me semble que c'est 6 secondes, limiter les requêtes a une fois toutes les 6 secondes me parait déjà un premier pas pour éviter la saturation de l'API par les bots...

Exemple de bot : https://www.candibot.fr

Mentions légales avec le numéro de téléphone du responsable : https://www.candibot.fr/information/legal
Attention : le N° SIRET affiché ne correspond a aucune entreprise connue.

Peut être que ce paramétrage peut être fait via une gateway/firewall, il faudrait travailler avec des personnes de la sécurité/réseau au sein du ministère pour voir ce qu'il est possible de mettre en place.

Ces bots tuent quotidiennement l'égalité des chances dans l'obtention d'une date d'examen pratique à l'obtention du permis de conduire.
Ce dernier est vital a beaucoup de personnes pour des raisons personnelles ou professionnelles.

**Comment by EdouardStick1** [comment]
Il y a aussi CandiNotifier qui n'a aucun numéro de siret dont le discord est :
https://twitter.com/CandiNotifier/status/1302751196575301635

Il facture un service payant de réservation automatique.

Pouvez-vous m'indiquer la procédure à suivre pour dénoncer une activité non déclarée ? 

En attendant, j'ai contacté le fisc pour qu'ils démarrent une enquête.

**Comment by scesardev** [comment]
Le plus important n'est pas la dénonciation bien que possible mais surtout faire en sorte que le **service Candilib ne puisse pas être utilisé à mauvais escient** et de façon déséquilibrée entre les candidats.

Candibot, CandiNotifier, vendeurs de créneaux sur Discord, il y en a une pelletée.

Par quel site/formulaires avez-vous effectué le signalement ?

Je n'ai pas trouvé de formulaire ailleurs mais il existe ce site : https://www.internet-signalement.gouv.fr/
Et on peut signaler une escroquerie (cela devra se faire par téléphone).

**Comment by Elliot8212** [comment]
> Il y a aussi CandiNotifier qui n'a aucun numéro de siret dont le discord est :
> https://twitter.com/CandiNotifier/status/1302751196575301635
> 
> Il facture un service payant de réservation automatique.
> 
> Pouvez-vous m'indiquer la procédure à suivre pour dénoncer une activité non déclarée ?
> 
> En attendant, j'ai contacté le fisc pour qu'ils démarrent une enquête.

Après vérification, le SIRET de candibot est un faux, il n'est greffé à aucuns registres.
Par contre il me semble que candinotifier déclare, même si il ne montres pas son siret, à vérifier auprès d'eux.

**Comment by scesardev** [comment]
Bonne nouvelle avec la dernière release les appels auront une limite.

https://github.com/LAB-MI/candilibV2/releases/tag/v2.9.5-beta8

A voir si ça équilibre, diminue ou règle le problème.

**Comment by Elliot8212** [comment]
Les limites pour le GET sont pas assez réduites encore, il faudrait aussi diminuer la quantité.

**Comment by baudointran** [comment]
Limitation fait

**Comment by scesardev** [comment]
Merci
