### ISSUE TITLE
Créneaux non visibles durant période de pénalité

### ISSUE THREAD

**Issue by NeutrinoXY** [LAB-MI/candilibV2#1301]
Durant la période de pénalité de 45 jours, les créneaux n'apparaissent pas, y compris ceux étant en dehors de cette période. Cela oblige l'utilisateur à attendre 45 jours avant de pouvoir réserver un créneau, ce qui constitue une double pénalité.

Une solution simple serait de rendre tous les créneaux visibles, et de refuser l'inscription lorsqu'un utilisateur tente de s'inscrire à un créneau dans cet intervalle de 45 jours.

**Comment by baudointran** [comment]
Bonjour,

`Durant la période de pénalité de 45 jours, les créneaux n'apparaissent pas ` : Oui, c'est exact. Sur cette période les créneaux n'apparaissent pas.
`y compris ceux étant en dehors de cette période`: Non, les créneaux au-delà de cette période doivent apparaitre.

D’après nos tests, les créneaux au-delà de la période de pénalité apparaissent.
