### ISSUE TITLE
ETC -  ne pas voir les éléments techniques dans le référencement  sur Google

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#1305]
- [x] le contenu de la balise no script ne doit pas apparaitre
- [ ] le "launch" dans le titre FAQ ne devrait pas être présent.

Lié à #1256

**Comment by baudointran** [comment]
NOK
Les noms icons sont toujours présents dans le référencement

**Comment by infosteph** [comment]
@baudointran : il me semble que ce point est désormais corrigé. Peut-on clore cet issue ?

**Comment by infosteph** [comment]
@baudointran : il me semble que ce point est désormais corrigé. Peut-on clore cet issue ?
