### ISSUE TITLE
Limitation API via IP

### ISSUE THREAD

**Issue by Elliot8212** [LAB-MI/candilibV2#1307]
Afin d'empêcher les bots de nous prendre toutes les places, il faudrait pouvoir limiter le nombre de connexions sur une même adresse IP, sur le site ou l'API, en plus des limitations GET/POST.

**Comment by baudointran** [comment]
Bonjour,

Merci, nous essayons d'équilibrer tous çà.
Ce ticket sera fermé. il ressemble à la  #1295.
