### ISSUE TITLE
Site inutilisable

### ISSUE THREAD

**Issue by Elliot8212** [LAB-MI/candilibV2#1314]
Les bots prennent TOUTES les places et massacrent le site.
Faites quelque chose s'il vous plaît ! 
Les limitation d'API ne servent apparemment pas...

Sur ce site le gars fait même payer pour accéder à une liste d'attente sur son bot :
https://www.candibot.fr/auto-registration

Je vous laisses vérifier par vous-même ,chaque jours toutes les places sont prises...
Il faut absolument changer des choses sur l'API, je ne sais pas quoi mais en l'état, le site est rendu inutilisable.

**Comment by SantaFee92** [comment]
Je confirmes il faut que candilib fasse quelque chose sur son API, 
on a plus aucunes places si on paie pas le bot.

**Comment by Elliot8212** [comment]
Un autre bot qui passes par l'API :
https://github.com/tritus/candilibre

**Comment by Elliot8212** [comment]
Aujourd'hui encore TOUTES les places prises sur l'API par les bot.
Faudrait peut-être empêcher certaines fonctions sur l'API plutôt que des limitations non ?

**Comment by SantaFee92** [comment]
> Aujourd'hui encore TOUTES les places prises sur l'API par les bot.
> Faudrait peut-être empêcher certaines fonctions sur l'API plutôt que des limitations non ?

Effectivement il y a quelque chose à faire au niveau de l'API !
Si ça continue je me casse sur un autre site...

**Comment by Elliot8212** [comment]
@jclaudan

**Comment by Elliot8212** [comment]
Si c'est encore comme ça demain, je dev une appli qui passe par l'API et je la file gratuit à tout le monde, tant pis.

**Comment by jclaudan** [comment]
Bonjour @Elliot8212,

Merci pour votre participation au débat, nous réfléchissons déjà à divers scénarios, malheureusement toutes les décisions ne dépendent pas seulement de notre équipe.

À bientôt

**Comment by xsaprtt** [comment]
Madame, Monsieur,



Étant inscrite sur la plateforme Candilib depuis plusieurs mois, et après une lutte acharnée pour trouver une place, j’ai eu la « merveilleuse » surprise de recevoir un mail de votre part m’indiquant que mon examen au permis de conduire à Melun le 30 Septembre à 15h a été annulé. 

Ayant tout prévu pour le jour-j, j’ai dû encore une fois faire mes recherches pour trouver un moniteur disponible pour m’accompagner et donc m’organiser en vue de passer mon examen dans de bonnes conditions. Je suis étudiante et je n’ai pas les moyens de débourser encore de l’argent pour trouver un moniteur. 

Ce n’est pas normal que mon examen ai été annulé à moins de 5 jours de mon passage et de redevoir passer par votre plateforme pour trouver une nouvelle fois une place d’examen. Il serait donc approprié qu’une nouvelle place me soit attribué au plus vite afin d’être prioritaire sur les autres candidats. 

Je vous remercie d’avance de votre réponse, en vous souhaitant une agréable journée,

Cordialement, 

Amandine
