### ISSUE TITLE
Proposition : Implémenter une liste d'attente pour les candidats

### ISSUE THREAD

**Issue by Jimmy9130** [LAB-MI/candilibV2#1319]
Bonjour,

Afin d'éviter aux candidats de se connecter tous les jours à midi pile pour obtenir une place, il serait utile de développer une **liste d'attente**.

Le principe de cette liste d'attente serait de **distribuer les places aux candidats en fonction de leur date d'inscription sur cette liste** (et aussi en fonction, pourquoi pas, de leur choix de centre d'examen).

Dès qu'une date est disponible, on recherche le premier candidat inscrit sur la liste d'attente, puis on le dépile.

Cela permettrait d'accroître l'égalité des chances entre candidats, de se prémunir contre les bots proposant des places de manière payante, et d'améliorer le confort d'utilisation du site.

Bon courage pour les développements.

**Comment by jclaudan** [comment]
Bonjour @Jimmy9130 ,

Merci pour votre participation, nous réfléchissons déjà à divers scénarios, malheureusement toutes les décisions ne dépendent pas seulement de notre équipe.

À bientôt

**Comment by Jimmy9130** [comment]
Je comprends. Merci pour votre réponse !
