### ISSUE TITLE
Les Régions ne s'affichent pas 

### ISSUE THREAD

**Issue by Elliot8212** [LAB-MI/candilibV2#1320]
Depuis hier lorsque je me connectes, les régions ne s'affichent pas et j'ai un message d'erreur en bas de page.

**Comment by Elliot8212** [comment]
J'ai un message d'erreur "429 Too many request" je ne comprends pas

**Comment by jclaudan** [comment]
bonjour @Elliot8212, pouvez-vous m'envoyer une capture d'écran svp?

**Comment by Elliot8212** [comment]
https://ibb.co/2NHqhLB

**Comment by jclaudan** [comment]
Voici une description de l'erreur, https://developer.mozilla.org/fr/docs/Web/HTTP/Status/429, avez vous aussi une capture d’écran avec le message "429 Too many request" ?

**Comment by Elliot8212** [comment]
https://ibb.co/PZPnZNC

**Comment by Elliot8212** [comment]
du coups je dois faire quoi ?

**Comment by Elliot8212** [comment]
en essayant d'avoir ma place j'ai spam le bouton pour valider ,ça viendrai de la ?

**Comment by laruiss** [comment]
Oui, tu as atteint une limite, en effet.

**Comment by Elliot8212** [comment]
> Oui, vous avez atteint une limite, en effet.

et du coups je dois attendre combien de temps maintenant ?....

**Comment by Leinadio** [comment]
Hello, il semblerait que j'ai également le même souci
