### ISSUE TITLE
Ajouter un Captcha lors de la réservation

### ISSUE THREAD

**Issue by Elliot8212** [LAB-MI/candilibV2#1327]
Pouvez-vous ajouter un captcha lors de la réservation de places pour empêcher les bot sur l'API ?
Je pense que c'est le plus simple et on en parles plus des bots, vous faut pas une autorisation pour ça non ?

Merci

**Comment by Elliot8212** [comment]
@baudointran 
@jclaudan

**Comment by Nono4726** [comment]
+ 1 Il s'agirait de mettre un anti-bot rapidement, certaines personnes font payer les places acquises grâce a des bots, il n'est quasiment pas possible pour les utilisateurs normaux de récupérer une place, c'est n'importe quoi...

**Comment by Elliot8212** [comment]
Pas de réponse, on commence à se demander si c'est pas quelqu'un de chez vous qui fait les bot pour se faire du fric...

**Comment by LElgueddari** [comment]
Salut, 
J'en profite juste pour en remettre un couche. Il existe aujourd'hui des personnes qui profite de ça pour revendre de manière illégale et complètement injuste des créneaux sur candilib via la mise en place de Bot.
Si la mise en place d'un Captcha se trouve être la solution sur un plus long termes, un moyen rapide pour partiellement contrer cette pratique serait de raccourcir la durer de validité du lien que vous envoyer par mail (à une quinzaine de minutes). En effet la plus part des bot propose de booker un créneaux pour vous jouent sur le fait que le lien est valable trois jours pour réussir à récupérer des créneaux.
Regardez un peu sur twitter avec #candilib vous verrez ce qui s'y trame ! 

Merci

**Comment by yakhatape** [comment]
Si une implémentation de Code est trop onéreuse niveau projet peut être mettre en place un WAF en amont de votre API non ? car franchement en 2020 ne pas être en mesure de géré ce genre de traffic illégitime c'est assez triste. Vous pouvez largement faire du ban temporaire en mettant en corrélation différentes métadonnées de la requête [user-agent, ip, rps, etc...]
Car en effet je vois ma compagne galéré depuis plusieurs mois pour avoir une place ... Surtout que visiblement les frontaux ne tiennes pas la charge versus les API donc les "clients" lambda passant par vos frontaux seront toujours piégé pour avoir la chance de réserver leur place ... Alors que les bots tape directement sur les API en Back ..

Bref je pense que si cela avait voulus être mis en place cela aurait déjà été fait donc bon, c'est juste histoire de jeter une bouteille à la mer

**Comment by yakhatape** [comment]
pour ceux qui veulent savoir qui est derrière candibot : 
https://www.infogreffe.fr/entreprise-societe/841398100-damiot-florian-750120A047380000.html?typeProduitOnglet=EXTRAIT&afficherretour=true

https://www.linkedin.com/in/florian-d-b28570182/ .. tiens tiens un dev 🥇

**Comment by cryptobioz** [comment]
@baudointran @jclaudan

Pourriez-vous nous dire pourquoi des solutions comme la mise en place d'un captcha lors de la réservation d'une place ou la création de listes d'attente dans les centres n'ont toujours pas été mises en place ?

Il s'agit d'un problème important qui ne devrait pas être ignoré. Si c'est un choix volontaire de votre part, je vous invite à l'expliquer clairement ici.

Si ce problème n'est pas corrigé à cause d'un manque de moyens de votre côté, je peux commencer à travailler sur une PR. Je suis persuadé que d'autres personnes seraient également prêtes à travailler là-dessus à condition d'avoir votre soutien. Nous devons être sûr que si une PR est proposée, elle sera examinée et que les échanges qui s'en suivront mèneront au merge de cette PR et au déploiement du fix dans les plus brefs délais. La communauté est prête à vous aider mais nous ne souhaitons pas perdre notre temps.

**Comment by liberforce** [comment]
Je confirme, ma femme a dû s'inscrire sur un de ces bots pour avoir une chance de trouver une place (chose que je ne cautionne pas, mais peux comprendre), au détriment bien sûr des personnes qui veulent s'en sortir honnêtement. On est donc en présence de gens qui prennent une ressource gratuite et la rendent payante, et s'engraissent sur le dos des centaines de gens qui n'ont pas forcément d'énormes moyens. Ces bots doivent être bannis d'une manière ou d'une autre. N'y a-t-il pas déjà moyen de le faire d'après les conditions générales d'accès au service, ou d'utilisation de l'API ? Ça me parait critique.

**Comment by cryptobioz** [comment]
@infosteph @odjpromi

Êtes-vous au courant de ce problème ? Est-ce que des contre-mesures sont à l'étude ?

**Comment by liberforce** [comment]
Je vois qu'il y a une pull request en cours: #1360 

@baudointran : que manque-t-il pour pouvoir la comptéter ?

**Comment by machined88** [comment]
Bonjour, l'issue est-elle toujours d'actualité ?

**Comment by infosteph** [comment]
Bonjour @machined88 @liberforce @cryptobioz @yakhatape @LElgueddari @Elliot8212 @Nono4726 ,
Je vous remercie pour l'ensemble de vos retours, interrogations et sollicitations.
Nous souhaitons, comme en témoigne l'issue #1360, mettre en place un captcha lors de la réservation de place.
Notre contrainte est interne (politique SSI). Nous ne pouvons utiliser un système de captcha non auto-hébergé (en service tiers donc). Nous devons utiliser un système de captcha "self-hosted". Nous avons identifié quelques solutions mais sommes toujours à la recherche d'une solution performante et respectueuse de la vie privée de nos usagers. Nous acceptons vos propositions pour avancer.
Merci pour votre aide !
Très cordialement,
Stéphane

**Comment by liberforce** [comment]
Bonjour @infosteph, merci pour ce retour.

Personellement, je déteste les captcha, tout simplement parce que même pour quelqu'un sans soucis particulier de vision comme moi, ils sont parfois extrêmement difficiles à lire. Il y a des alternatives plus intéressantes, comme poser une question assez simple (type addition ou soustraction), utiliser des sliders, etc., cf: https://www.experienceux.co.uk/ux-blog/5-alternatives-to-captcha-that-wont-baffle-or-frustrate-users/

**Comment by Nono4726** [comment]
Bonjour @infosteph ,
Je pense que vous ne vous rendez pas compte de la situation actuelle de votre plateforme.
La vérité c'est que depuis depuis des mois il n'est pas possible de réserver une place sans acheter les services d'un bot (candibot) ou d'attendre d'entrer dans le groupe 1. C'est à dire que le bot prends les places avant même que les utilisateurs normaux puissent les voir. Il y a déjà eu des jours où il avait de nombreuses dates disponibles sur des centres (plus de 15) pour les groupes 2 voire 3. Elles ne s'affichent même pas sur notre écran étant donné que le bot les prends avant. Ceci n'est pas faute à ma connexion étant donné que j'ai un très bon débit, je suis fibré. Plusieurs de mes contacts rapportent le même constat. C'est tout simplement alarmant que rien ne soit fait depuis PLUSIEURS MOIS. Les développeurs de candibot ont carremment eu le temps d'optimiser leur bot comme il le faut.

Rien qu'un système de connexion plus complexe freinerai le problème, il est trop facile de donner le lien de connexion ephemere au bot.

**Comment by machined88** [comment]
> 
> 
> Bonjour @infosteph ,
> Je pense que vous ne vous rendez pas compte de la situation actuelle de votre plateforme.
> La vérité c'est que depuis depuis des mois il n'est pas possible de réserver une place sans acheter les services d'un bot (candibot) ou d'attendre d'entrer dans le groupe 1. C'est à dire que le bot prends les places avant même que les utilisateurs normaux puissent les voir. Il y a déjà eu des jours où il avait de nombreuses dates disponibles sur des centres (plus de 15) pour les groupes 2 voire 3. Elles ne s'affichent même pas sur notre écran étant donné que le bot les prends avant. Ceci n'est pas faute à ma connexion étant donné que j'ai un très bon débit, je suis fibré. Plusieurs de mes contacts rapportent le même constat. C'est tout simplement alarmant que rien ne soit fait depuis PLUSIEURS MOIS. Les développeurs de candibot ont carremment eu le temps d'optimiser leur bot comme il le faut.
> 
> Rien qu'un système de connexion plus complexe freinerai le problème, il est trop facile de donner le lien de connexion ephemere au bot.

Je suis d'accord, de ce fait il ne faut pas s'étonner quand on saute sur une place pour ensuite pouvoir la modifier car celles-ci sont vraiment rares. La suppression de la modification de places est devenu plus un handicap qu'autre chose maintenant.

**Comment by ynerant** [comment]
Bonjour,

J'ai constaté qu'un captcha a bien été intégré à Candilib, au moment de la réservation de dates.
Cependant, celui-ci n'est pas suffisant. À vrai dire ... Il est très facile à casser.

Candibot reste encore un fléau. Je constate au vu de leurs statistiques qu'environ 1 place sur 2 est réservée via Candibot. Ainsi, toute personne honnête qui ne souhaite pas offrir 15 € à une société qui profite de l'absence de place sur Candilib pour se faire de l'argent (pourquoi demander 15 € ??) dans les groupes de 12h30/12h40 voire 12h20 peuvent très difficilement pouvoir réserver une place normalement, et ça se constate très bien en pratique.

Attendant actuellement une place dans le groupe de 12h30 et consterné par ce modèle économique, j'ai voulu développer mon propre bot qui réservera ma place pour moi. Je dispose actuellement d'une version fonctionnelle (testé sur une installation locale de Candilib, vive le logiciel libre), et si rien ne bouge je m'en servirai pour réserver ma place d'examen. Le but n'est pas d'imiter Candibot mais de l'affronter à arme égale. Programmer cela m'amuse, et je n'y vois aucun intérêt personnel derrière (hormis une place en examen), il s'agit avant tout d'un projet personnel et ne veux en tirer aucun bénéfice ; si le projet grandit il sera mis à disposition de tout le monde gratuitement et surtout dans le respect intégral des données des gens (c'est actuellement l'étape difficile).

Je diffuserai le code source prochainement, j'ai quelques détails à fignoler avant.

Pour revenir au captcha, il ne m'a pas fallu plus de 30 minutes pour le casser. Le nombre d'images est fini, je connais les différentes images, j'associe le nom à chaque image et c'est terminé. Pas exactement : le code des images changent, mais pas leurs pixels; une conversion dans un format d'image brut suffit à casser le captcha.
Ce type de captcha est très bien pour bloquer les spambots, pas pour bloquer Candibot qui est capable de contourner ce type de sécurité.

Cependant, pour ne pas dire que du mal de Candibot, certaines bonnes idées sont proposées, notamment en termes de statistiques. Connaître le nombre de places attribuées par centre aide à savoir à quoi s'attendre et ne pas garder Candilib derrière une boîte noire obscure, à savoir quel centre viser et de savoir dès 12h si cela vaut le coup d'attendre son tour pour réserver une place. Ce type de statistiques pourrait être proposé publiquement par Candilib, on ne devrait avoir à utiliser un service tiers.

Ensuite, je trouve que le principe de files d'attente plutôt bon et plus juste que le shotgun. Les candidat⋅e⋅s pourraient donner leurs disponibilités et Candilib attribuerait automatiquement une place, un peu comme Parcoursup. Néanmoins, la confirmation de présence d'un⋅e accompagnant⋅e et d'une voiture double-commande pourraient ne pas avoir de sens, mais il n'est de toute façon pas possible en 4 secondes actuellement de contacter son enseignant⋅e pour avoir ses disponibilités lors de la réservation du créneau, donc je pense que cela ne changerait rien. Une telle file d'attente pourrait s'avérer plus juste et pénaliserait beaucoup moins les personnes ayant manqué un créneau fatidique une fois. Cela réduirait également beaucoup le stress, car il ne serait plus du tout indispensable de se connecter tous les jours pour espérer avoir une place : une notification par mail suffirait. Dans tous les cas, cela rendrait inutile l'utilisation de bots externes et rendrait l'utilisation de Candilib plus équitable envers les candidats.

Candibot ou n'importe quel autre bot répond à un besoin : les places sont au shotgun, il faut réserver vite avant tout le monde. C'est à Candilib de répondre à ce besoin, et non à un quelconque bot. Une fois ce besoin résolu, alors les bots ne seront plus d'aucune utilité et il ne sera pas utile de chercher à les bloquer par un quelconque captcha.

Bien sûr, une autre solution serait d'augmenter dratiquement le nombre de places d'examen en candidat libre ...
