### ISSUE TITLE
Archiver une réservation lors d'annulation ou modification (8)

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#140]
En tant que tech, je dois pouvoir retrouver toutes les réservations passées par un candidat :

- Les informations de la place (centre, date, inspecteur)
- La date de réservation
- La date d'annulation (la modification correspond en fait à une annulation d'une place et la réservation d'une autre)
- Les informations du candidat

- [x] Si le candidat annule une place, cette place doit être archivée dans le document du candidat
- [x] Si le candidat modifie une place, la place libérée doit être archivée dans le document du candidat
- [ ] Si le candidat est archivé et qu'il a une réservation, sa place doit être archivée dans le document du candidat
- [ ] Si la place est supprimée (par un admin/répartiteur), la place doit être archivée dans le document du candidat qui l'avait réservée

**Comment by baudointran** [comment]
impacts possibles:
- [ ] Annulation d'une reservation
- [ ] Suppression d'un candidat
- [ ] Suppression d'une place 
- [ ] Suppression d'un centre  ( cas qui ne doit pas arrivé )
- [ ] Suppression d'un inspecteur  ( cas qui ne doit pas arrivé.)

Questions:
- A-t-on besoin d'indiquer dans l'archive que la place est supprimé par l'administrateur?
- A-t-on besoin d'indiquer que la place à changer d'inspecteur?
- Quand le candidat est archivé doit-on conserver les places archivés?
