### ISSUE TITLE
Modifier ma réservation (8)

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#141]
ETC je peux modifier ma réservation : je peux recommencer tout le parcours pour choisir une nouvelle place, et confirmer que je peux changer ma réservation.

À définir : les règles des 10 (ou x) jours accessible uniquement aux VIP.

Envoyer un mail d'annulation avant un mail de convocation

**Comment by baudointran** [comment]
Impacts :
 - [ ] Obtenir la liste des centres avec le nombre de place
 - [ ] Obtenir la liste des places
 - [ ] Enregistrement de la réservation (vérification de la date de réservation)
