### ISSUE TITLE
Dates selon les priorités 

### ISSUE THREAD

**Issue by marvvmaii** [LAB-MI/candilibV2#1410]
Bonjour,

J'aimerais savoir comment fonctionne le système de priorité ?

En effet on a pu établir le constat suivant : 

Janvier Février Mars Avril Mai  : entre 12h et 12h20
Juin Juillet août : 12h20 a 12h30
Septembre Octobre Novembre Décembre : 12h40 a 12h50

Mais les personnes inscrites en Juin par exemple monte d'un niveau après ? Est-ce que les personnes de 12h20 vont-ils pouvoirs regarder les horaires a 12h10 ?

Qu'en est-il des personnes pénalisés ?

Merci pour vos réponses. Bon courage

**Comment by infosteph** [comment]
Bonjour,
Pour obtenir les réponses à ces questions, je vous invite à interroger le répartiteur présent sur votre département d'inscription.
Pour se faire, il convient d'utiliser le formulaire de contact dédié : https://beta.interieur.gouv.fr/candilib/contact-us
S'agissant des personnes pénalisées, vous trouverez plus d'informations au sein de notre foire aux questions :
https://beta.interieur.gouv.fr/candilib/faq
Bien cordialement,
