### ISSUE TITLE
Présenter uniquement les créneaux que j'ai le droit de réserver

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#142]
ETC je vois les créneaux que je peux réserver et uniquement ceux-ci : cette vérification doit se faire côté serveur.

À définir : les places des 10 (ou x) prochains jours ne doivent être visibles que pour les VIP.

**Comment by baudointran** [comment]
Impacts fonctionnalité: 
- [ ] : Model de données du candidat ( ajout de flag: VIP, echec examen, annulation ) 
- [ ] : Obtenir la liste des centres avec le nombre de place
- [ ] : Obtenir la liste des places 
- [ ] : Enregistrement de la réservation (vérification de la date de réservation)
