### ISSUE TITLE
Impossible d'utiliser le formulaire de contact

### ISSUE THREAD

**Issue by edouardmenayde** [LAB-MI/candilibV2#1421]
Bonjour,

Je suis utilisateur de la plateforme et je n'arrive pas à me connecter à celle-ci.
Mais je n'arrive pas non plus à utiliser le formulaire de contact (le bouton d'envoi est grisé) pour faire remonter mon problème malgrès qu'il soit entièrement rempli et qu'aucune erreur n'est visible (rien en rouge, rien dans la console)
.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/6023858/104128152-2e179880-5366-11eb-83dd-117f644b7e1c.png">
(Pour des raisons de confidentialité j'ai évidemment mis un faux numéro NEPH).

Pouvez-vous entre temps me donner un email de façon à ce que je puisse contacter quelqu'un pour mon problème de connexion ?

**Comment by infosteph** [comment]
Bonjour,
N'avez-vous pas oublié de compléter l'objet du message ?
Bien cordialement,

**Comment by edouardmenayde** [comment]
Bien vu merci
