### ISSUE TITLE
Des places annulées ne reviennent pas à la liste disponible immédiatement

### ISSUE THREAD

**Issue by Junru** [LAB-MI/candilibV2#1442]
Bonjour, 

J'ai relevé qu'il existe un problème en cas d'annulation de place : 
Quand la place a été annulée par l'utilisateur, cette place ne rentre pas immédiatement à la liste disponible.  

Est-ce que c'est déjà prévu ? 
Ce problème peut être utilisé par les personnes (groupe priorisée) qui veulent bloquer leur places en attendant un créneau préférable pour eux, et les utilisateurs moins priorisé n'auront plus la place à réserver dans leur tours.

Bien cordialement

**Comment by infosteph** [comment]
Bonjour @Junru,
Les places libérées sont remises à disposition sur la plateforme Candilib le lendemain à 12h00.
Bien cordialement,
