### ISSUE TITLE
Prévevnir les utilisateurs avant une mise à jour majeure du site.

### ISSUE THREAD

**Issue by machined88** [LAB-MI/candilibV2#1449]
Bonjour,

J'ouvre cette issue car je trouve que vous n'informez pas assez les utilisateurs de Candilib des mises à jour qui peuvent intervenir sur le site et modifier son fonctionnement. 

Par exemple, j'avais réservé une place d'examen durant le mois de décembre pour janvier à Saint-Germain-en-Laye que j'ai décidé d'annuler pour empêchement personnel (études). Deux jours après, la répartition des groupes est instaurée et je découvre que je n'ai accès sur le site seulement à 12h50 sans quelconque prévention de votre part. J'ai donc décidé de prendre une place pour Saint-Priest car j'ai besoin de permis pour mon stage très rapidement mais que se passe-t-il si j'ai un autre empêchement ? Une pénalité de 45 jours ? Et là encore personne n'est prévenu à l'avance de ce changement sur le site, le seul moyen de s'en informer étant de scruter les différentes "pull requests" dont seul les personnes s'intéressant au minimum au développement d'applications peuvent comprendre.

Voilà, ceci est un exemple parmi tant d'autres et je suis sûr que beaucoup d'autres personnes sont d'accord pour dire qu'il y a un manque de communication entre les développeurs de Candilib et ses utilisateurs quotidiens. Pour y remédier, pourquoi pas mettre les bandeaux d'informations bleus quelques jours avant l'application de la MàJ (exemple : "A partir du [date], [expliquer la mise à jour]."), ce serait franchement bénéfique.

Cordialement.

PS : J'ai bien conscience du problème des bots sur ce site qui nuit au fonctionnement de ce dernier mais instaurer un reCAPTCHA n'est-il pas suffisant ? J'observe que la pull-request a été bloqué.

**Comment by infosteph** [comment]
Bonjour,
La possibilité de communiquer sur les modifications apportées à l'application Candilib n'appartient pas à l'équipe chargée de son développement et de sa maintenance. Cette communication est portée et validée par sa maîtrise d'ouvrage, la délégation à la sécurité routière. 
Nous vous invitons à remonter votre message sur https://www.securite-routiere.gouv.fr/page-contact
Bien cordialement,
