### ISSUE TITLE
Nombreuses imperfections de la plateforme

### ISSUE THREAD

**Issue by kevinbioj** [LAB-MI/candilibV2#1460]
Bonjour,

Je viens ici en tant que porte-parole non officiel de nombreux candidats soufflant rien qu'à l'idée d'entendre ce nom, **Candilib**.
Sachez que cela n'a rien de personnel contre l'équipe de développement, dont le travail est louable, après tout ce ne sont pas eux qui dictent le fonctionnement de la plateforme.

### Le flou dans le fonctionnement
Premier point à souligner, la plateforme est très obscure à l'utilisateur. Bien que simple, il est assez difficile de comprendre toutes les subtilités à première vue. L'exemple parfait serait celui des groupes : pourquoi les avoir instaurés, comment fonctionnent-ils, comment sont répartis les candidats et surtout **quand est-ce qu'un candidat change de groupe**.

La pénurie criante de places d'examen fait que le message "Pas de place disponible pour le moment" est plus que récurrent, si bien qu'en réalité on ne voit que cela tous les jours. Cependant, c'est à se demander si le site fonctionne : on a rapidement l'impression qu'aucune place n'est jamais attribuée.

Sans vouloir me la jouer psychologue, cela décourage assez rapidement les gens (on le voit bien en cherchant "Candilib" sur Twitter) de ne pas avoir d'horizon et d'informations globales sur la plateforme. Il serait sympathique d'avoir des statistiques sur les places attribuées chaque jour, par département, ne serait-ce que pour montrer que cette plateforme vit et qu'on en sort un jour.

### Le grand rush du midi
Deuxième point, c'est ce que j'appelle "le grand rush du midi".
Candilib devient, entre 12h et 12h50, un grand Battle Royale qui va déterminer qui va enfin pouvoir passer son permis de conduire.
Bien que cela fonctionne, je me questionne sur l'éthique de la chose.

Plusieurs points ressortent de cela : 
- Tous les candidats ne sont pas disponibles à midi > cela crée une rupture d'égalité
- Nous n'avons pas tous la foi de rafraîchir 500 fois la page lorsque c'est à notre tour > on ne sait pas quand les places sont réellement libérées
- Tout le monde n'est pas aussi rapide à réserver une place > les phénomènes de race-condition entre deux candidats sont très certainement monnaie courante
- Il est alors très facile de déployer des bots qui vont détruire l'UX à voler les places aux "honnêtes" candidats > il est alors mission impossible d'utiliser nous-même le site, et cela nous force à utiliser ces bots puisqu'au final nous n'aurons pas de place sans

### Les bots rendent l'expérience affreuse
Troisième point, certainement le plus important : c'est l'affluence des bots qui promettent une place d'examen rapidement.
Candilib possède deux particularités : être open-source, utiliser Vue.js. Bien qu'il n'y ait rien à redire de ces deux points, on ne peut nier une chose : il est alors très facile de voir comment fonctionne toute cette machinerie.

Certains l'ont bien compris et en ont profité pour créer des bots qui ont pour promesse : nous offrir une place, rapidement.
Si ça s'arrêtait là, ce serait problématique mais ça passerait encore. Or, certains de ces bots font facturer leurs prestations une quinzaine d'euros (qui consiste en trois ou quatre requêtes, qui plus est).

On contraint donc des utilisateurs à **payer** puisque de toute manière, il pourront toujours courir pour obtenir une place par eux-mêmes. C'est assez lunaire qu'aucune mesure ne soit mise en place pour contrer les bots, ne serait-ce que des captchas  ou du ratelimiting au niveau de l'API pour "limiter" la casse.

La popularité de ces bots tient probablement à l'utilisation de ces fameux "Magic-link" au lieu du traditionnel mot de passe. Je vous l'accorde, c'est très pratique puisque vous n'avez pas à prendre le risque de gérer les mots de passe utilisateur. Cependant, pour beaucoup de gens ce lien ne fait "rien de mal", ce n'est pas un mot de passe ? C'est juste un lien, qu'est-ce que ça pourrait bien faire de mal ?

On a donc des gens qui donnent un moyen d'authentification sur un site d'État à des particuliers qu'ils ne connaissent ni d'Adam ni d'Êve qui ont, avec un peu de chance, fait facturer la prestation. Bien qu'on ne puisse pas faire grand chose, ce lien donne quand même accès à l'identité du candidat, au numéro NEPH, son adresse email ainsi qu'à son numéro de téléphone.
Je n'ai pas connaissance de "scandales" liés à du spam provenant de ce genre de plateformes mais ça ne saurait tarder à mon goût, la tentation est quand même grande.

### Quelles solutions ?
Je ne prétend pas avoir la solution miracle pour chacun de ces problèmes, en revanche j'ai quelques pistes qui permettraient d'améliorer l'expérience utilisateur.

- **Accéder à des statistiques** pour montrer aux gens que la plateforme fonctionne, qu'il n'y a des gens qui se voient attribuer des places et qu'ils verront, un jour ou l'autre, le bout du tunnel.
- **Arrêter ce rush** et plutôt proposer personnellement des rendez-vous (par email, ou lors de chaque visite ponctuelle) qui pendant une durée limitée (24 heures par exemple) proposeraient un créneau au candidat, et qui seraient proposées à autrui si il y a refus ou expiration du délai.
- **Avertir les utilisateurs** sur les dangers de ce lien et surtout ce qu'il représente, et commencer à prendre de sérieuses mesures contre ces bots car c'est très certainement le problème le plus inadmissible parmi tout ce qu'on peut dire de Candilib.

Ouvert à la discussion, bien sûr.
En espérant que cela soit pris en compte.

**Comment by Keke27210** [comment]
OVH a brûlé, aussi triste soit-il, profitez des prochains jours qui viennent : Candibot est mort pour l'instant, et peut-être d'autres services.
Cependant cela ne résout pas le problème de base.

**Comment by Keke27210** [comment]
Deux mois sont passés... pas grand chose ne s'est fait... et ça s'est même empiré.

La tentative de captcha était très bonne, mais manifestement pas assez puisque ce dernier a été explosé en très peu de temps par Candibot. Ainsi, le bot continue de réserver instantanément des places tandis que les humains se retrouvent confrontés à un nouvel obstacle rallongeant le temps nécessaire pour une réservation... ce qui en réalité empire le problème.

La fin des groupes pour certains départements, c'est bien aussi... mais du coup c'est au final moins bien. Imaginons une personne du groupe 3, le bot vole toutes les places pour les personnes inscrites jusqu'au groupe 3... mais peut éventuellement bénéficier des places restantes avant que ce soit au tour du groupe 4.
Maintenant, avec les bots, les places seront (j'imagine, on verra d'ici peu, pour le 76 du moins) toutes instantanément prises sans négociation possible.

Je ne reviens pas sur l'aspect comportemental de l'application ni sur son design, mais sur le plan technique c'est tout de même dingue qu'il n'y ait toujours pas de rate limiting. Alors peut-être sont-ils bien préparés et dispatchent les réservations sur plusieurs machines, mais je doute qu'il y ait une IP source par réservation de bot. Une limite d'une requête toutes les 20 secondes sur l'endpoint de réservation serait, je pense, assez efficace dans un premier temps.
