### ISSUE TITLE
Problème affichage dates des centres au cours de la navigation

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#153]
la première sélection d'un centre affiche la liste des dates ayant des places disponibles
suite à un retour arrière en cliquant sur le nom du centre en haut et la sélection d'un nouveau centre, on affiche toujours les dates des places disponibles du centre précédent.
si on refais la manip (retour arrière et sélection du même deuxième centre) on affiche bien les dates et places disponibles pour ce centre.

**Comment by jclaudan** [comment]
fix issue with branch #98
