### ISSUE TITLE
Bad Token

### ISSUE THREAD

**Issue by JCluzet** [LAB-MI/candilibV2#1675]
Hello ! 
Merci pour la creation du logiciel, cependant impossible d'envoyer le lien reçu par mail, il m'indique  chaque fois `API CALL ERROR on candidat/places : Bad token` , comment faire sachant que le lien est bien copié.. 
Merci!

**Comment by baudointran** [comment]
Bonjour,

Il semble que ce message ne font pas parti de la liste des messages que nous renvoyons.
Pouvez-vous nous fournir plus de détail?
Sur quel navigateur utilisez vous ? quel est sa version ?
ou Pouvez-vous nous fournir un copie d'écran de ce message?

merci
