### ISSUE TITLE
Empêcher les candidats de réserver après un passage (délai) (5)

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#168]
ETC

- [x] Lors de la synchro Aurige, si j'ai passé le permis (et raté ou inadmissible ou autre), j'ai une pénalité
- [x] Lorsque j'essaie de réserver une place alors que j'ai une pénalité, et que cette place est avant la date minimale de ma pénalité, j'ai un message m'expliquant que je ne peux pas prendre cette place et pourquoi

- [x] Le texte du message doit correspondre à celui donné par le PO (@Evbern ou Fred)
**Cas impossibilité issue d'une date de passage trop récente (source Aurige) :**
```Vous avez échoué ou n'avez pas été admissible à l'examen pratique du permis de conduire le _date d'échec ou de non admission Aurige_. Un délai de repassage de 45 jours s'appliquant à partir de la date de votre dernier examen, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.```

**Comment by Evbern** [comment]
Le texte a été complété

**Comment by baudointran** [comment]
@Evbern
Le message doit-il apparaître après la confirmation de l'annulation ou de la modification?
@Evbern @jclaudan
Si oui, ce message n'est-it pas trop long pour snackbar ?
Si non, ce message n'est-it pas trop long sur le bandeau au dessus de la liste des créneaux ?

**Comment by Evbern** [comment]
@baudointran 
Le message doit apparaître lorsqu'un candidat a échoué ou n'a pas été admissible à l'examen pratique du permis et souhaite réserver un créneau avant de le délai de repassage.

@baudointran @jclaudan
Le message était un peu long, je l'ai raccourci comme suit :
```Vous avez échoué ou n'avez pas été admissible à l'examen pratique du permis le _date d'échec ou de non admission Aurige_. Un délai de repassage de 45 jours s'appliquant à partir de cette date, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.```

@baudointran
Je propose que ce message s'affiche en dessus de la liste des créneaux non disponibles, plutôt que dans le snackbar (un snackbar est bien un petit encart qui apparaît en bas d'une page ?)
