### ISSUE TITLE
Problème captcha

### ISSUE THREAD

**Issue by TimeTraveler87** [LAB-MI/candilibV2#1683]
Bonjour, je rencontre un problème pour réserver des places.
Je réussis à sélectionner un créneau horaire mais au moment de passer le test captcha les images n'apparaissent pas.

**Comment by baudointran** [comment]
@TimeTraveler87 , 
Bonjour,pouvez-vous nous donner plus de détail? Sur navigateur? un copie d'écran si possible? avez-vous reçu un message?

**Comment by TimeTraveler87** [comment]
@baudointran
![Captcha_Bug](https://user-images.githubusercontent.com/106354589/171951451-90ec194b-ad55-4c13-82fd-2c42e1479f43.png)
Je suis sur mozilla firefox pour info, et je reçois ces messages côté serveur après avoir fais la manipulation pour afficher la partie captcha : 
![Captcha_Server](https://user-images.githubusercontent.com/106354589/171952868-7d54136a-024f-4492-a15f-8344ed97d15e.png)

**Comment by baudointran** [comment]
Il semblerait que votre problème soit réglé
