### ISSUE TITLE
Empêcher résa si annulation récente (à moins de x jours, délai) (5)

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#169]
ETC, je suis pénalisé si j'annule ma réservation à moins de X jours, et par la suite, je ne peux réserver que les places à +45 jours.

- [x] J'ai annulé ma place alors qu'elle était dans moins de x jours, j'ai donc une pénalité
- [x] Si je suis pénalisé et que j'essaie de réserver une place à une date antérieur à mon délai de pénalité, je reçois un message pour m'expliquer que je ne peux pas réserver cette place et pourquoi.

**Cas impossibilité issue d'une annulation/modification de créneau à moins de X jours de la date d'examen (source Candilib)** :
```Vous avez annulé ou modifié votre réservation à moins de X jours de la date d'examen. Un délai de repassage de 45 jours s'appliquant à partir de la date de votre réservation annulée ou modifiée, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.```

**Comment by Evbern** [comment]
Le texte a été complété

**Comment by baudointran** [comment]
J'ai annulé ma place alors qu'elle était dans moins de x jours, j'ai donc une pénalité
Resolved on #182

**Comment by jclaudan** [comment]
ToDo: enlever la constante cote front PENALTY_DAYS
ToDo: enlever la constante NUMBER_OF_DAYS_BEFORE_DATE du front


variable  getReservation:
{
    lastDateToCancel,
    canBookAfter,
    dayToForbidCancel,
    timeOutToRetry,
}

**Comment by baudointran** [comment]
@Evbern
Le message doit-il apparaître après la confirmation de l'annulation ou de la modification?
@Evbern @jclaudan 
Si oui, ce message n'est-it pas trop long pour snackbar ? 
Si non, ce message n'est-it pas trop long sur le bandeau au dessus de la liste des créneaux ?

**Comment by Evbern** [comment]
@baudointran 
Le message doit apparaître après une **annulation**, lorsqu'un candidat souhaite réserver un nouveau créneau. 

@baudointran @jclaudan
Le message était un peu long, je l'ai raccourci comme suit :
```Vous avez annulé votre réservation à moins de X jours de l'examen. Un délai de repassage de 45 jours s'appliquant à partir de la date de l'examen annulé, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.```

@baudointran
Je propose que ce message s'affiche en dessus de la liste des créneaux non disponibles, plutôt que dans le snackbar (un snackbar est bien un petit encart qui apparaît en bas d'une page ?)

**Comment by jclaudan** [comment]
@Evbern voici un aperçu de ce que cela va donner sur un iphone 6/7/8

![image](https://user-images.githubusercontent.com/36130708/55464271-0628cc00-55fb-11e9-9f64-0b788ffaa865.png)

**Comment by Evbern** [comment]
@jclaudan @baudointran 
Ok merci ! Possible de réduire un peu la police et les marges en haut et en bas du texte pour que ça prenne un peu moins de place ?

**Comment by jclaudan** [comment]
sur 3 lignes au lieu de 5.
 
![image](https://user-images.githubusercontent.com/36130708/55472194-c1f1f780-560b-11e9-9618-7d32d126dce3.png)

**Comment by Evbern** [comment]
@jclaudan Ok pour le message

@jclaudan @baudointran 
- J'avais une réservation le 12 avril. Je l'ai annulée le 5 avril. J'étais donc dans la pénalité => le front est OK car j'ai bien eu le message m'informant de la pénalité.
- J'ai pu réserver ensuite un créneau à moins de 45 jours. La pénalité ne s'est donc pas appliquée.
