### ISSUE TITLE
Modifier le mail d'un candidat

### ISSUE THREAD

**Issue by ColineVL** [LAB-MI/candilibV2#1691]
Bonjour,
En tant que candidat nous ne pouvons pas modifier notre adresse mail. L'adresse mail avec laquelle je me suis inscrite va fermer dans une dizaine de jours et je serai donc incapable de recevoir les liens de connexion. 
Comment faire pour la modifier ?
Je suis candidat libre (auto-école En Voiture Simone) et je ne vois donc pas d'administrateur qui pourrait le faire pour moi.
Merci de votre aide.

**Comment by baudointran** [comment]
@ColineVL 
Bonjour,

Vous pouvez faire la demande le formulaire de contact https://beta.interieur.gouv.fr/candilib/contact-us
