### ISSUE TITLE
API: log erreur - DeprecationWarning: collection.findAndModify is deprecated

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#192]
L'erreur suivante est remontée par l'api:
> (node:18) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.

**Comment by laruiss** [comment]
@pli01 Est-ce que ça apparaît encore dans les logs récents ? C'est bien sur Candilib V2, ça ? parce que `findAndModify` est introuvable dans l'historique de la branche `develop`...
