### ISSUE TITLE
Wording de la FAQ

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#203]
Propositions :
- [x] remplacer la mention "Si vous devez annuler moins de 7 jours avant la date, vous serez placé en liste d'attente non prioritaire" par
```Si vous annulez moins de 7 jours avant la date d'examen, vous ne pourrez réserver un nouveau créneau que 45 jours après la date de votre réservation annulée.```
- [x] ajouter le cas suivant
```Si vous avez échoué ou n'avez pas été admissible à l'examen pratique du permis de conduire, vous ne pourrez réserver un nouveau créneau que 45 jours après la date de votre dernier examen pratique.```
- [x] ne pas mettre de retour à la ligne et de ":" après "Votre accompagnateur sera"
- [x] homogénéiser les espaces avant/après les deux points et les guillemets
- [x] mettre des bulletpoints pour clarifier la liste complète des documents à fournir le jour de l'examen

**Comment by laruiss** [comment]
@Evbern Pour le dernier point, est-ce que ça peut attendre la v2.1 ? Qui nous donnera ces contacts ? Est-ce qu'il faut prévoir un champs pour que le candidat indique un département ?

**Comment by Evbern** [comment]
@laruiss 
Pour la 2.0, je pense qu'il faut intégrer les contacts dans la FAQ pour éviter que le candidat soit dans une impasse. Frédéric pourra nous donner les contacts ce lundi.
Pour la 2.1, on pourra réfléchir au fait d'intégrer un champ pour rechercher le département, bonne idée !

**Comment by Evbern** [comment]
@laruiss OK
