### ISSUE TITLE
Message dans Candilib suite à la validation de l'adresse mail

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#206]
Anomalie :
- [x] Au format PC, le message dans Candilib est : "Votre email a été validé, veuillez …" Lorsqu'on bascule au format mobile IPhone XR, le message dans Candilib est en vert est changé en "Votre adresse courriel est déjà validée"

**Comment by laruiss** [comment]
Je ne comprends pas bien la procédure de reproduction du bug.

**Comment by laruiss** [comment]
Vu avec Evguen : ce n'est pas un bug.
