### ISSUE TITLE
Wording du mail informant de l'attente de vérification

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#207]
Proposition : 
- [x] Remplacer le texte par 
```Votre adresse email a été validée et votre demande d'inscription est en cours de vérification. Vous recevrez une information sous 48h hors week-end et jours fériés.```

**Comment by laruiss** [comment]
Ah, on ne met plus _courriel_ mais _email_, alors ? Si c'est le cas, il faut qu'on le remplace partout.

**Comment by Evbern** [comment]
Ok, commençons juste par la ponctuation.
Il me semble avoir vu parfois du _email_, parfois du _courriel_. Je regarde aujourd'hui et vous dis. L'objectif serait en effet d'homogénéiser.

**Comment by Evbern** [comment]
Ok @laruiss
