### ISSUE TITLE
Consulter la localisation d'un centre sur OSM ou Qwant maps

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#208]
Anomalie :
- [x] La localisation ne semble pas être toujours exacte
- [x] Le pointeur localisant précisément le centre sur la carte est absent

**Comment by laruiss** [comment]
Est-ce que c'est pour la 2.0 ou pour la 2.1 ?

**Comment by Evbern** [comment]
> Localisation : pour la 2.0 car la localisation semblait erronnée
> Pointeur : pour la 2.1 (sauf si effort minimum pour l'intégrer à la 2.0)

**Comment by laruiss** [comment]
La localisation exacte n'est pas possible pour certaines villes, parce que pour Rosny sous Bois, l'API officielle renvoie Rosny ss bois, et OpenStreetMap ne comprend pas ce 'ss'... Tant que nous n'aurons pas les latitude et longitude des centres, nous ne pourrons pas avoir mieux.

En revanche, dès que nous les aurons, ce sera facile de construire une URL à la fois précise et avec le pointeur :

https://www.openstreetmap.org/?mlat=48.84910&mlon=2.40670#map=20/48.84910/2.40670
