### ISSUE TITLE
Convocation reçue par mail : anomalie

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#211]
Anomalies : 
- [x] le lien du 3e bullet renvoie bien vers l'URL visé mais la page "Your connection is not secure" apparaît
- [x] les liens "notre aide en ligne" et "votre réservation" renvoient vers une page introuvable

**Comment by laruiss** [comment]
@baudointran Pour le premier point, il suffit de rajouter `www` devant `legifrance.gouv.fr`, l'adresse du lien devenant `https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033736411&categorieLien=id`

**Comment by baudointran** [comment]
les liens "notre aide en ligne" et "votre réservation" renvoient vers une page introuvable :
fixed on #226

**Comment by Evbern** [comment]
@laruiss @baudointran 
Le premier bug est toujours présent : "le lien du 3e bullet renvoie bien vers l'URL visé mais la page "Your connection is not secure" apparaît"
Le deuxième fonctionne
