### ISSUE TITLE
Convocation reçue par mail : améliorations

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#212]
Propositions : 
- [x] Ajouter après le numéro NEPH "sur le centre XXX à l'adresse" et supprimer l'espace et le retour à la ligne
- [x] Remonter les bullets carrés 3, 4 et 5 d'un cran
- [x] Ajouter "Vous apporterez" ou "Vous serez muni d'" avant "une enveloppe affranchie à 20g"
- [x] Remplacer le dernier bullet par
```Si vous avez fait l'objet d'une annulation de permis, vous apporterez le récépissé de la "fiche retour au permis de conduire" que vous aurez imprimé sur le site de l'ANTS.```
- [x] Remplacer le premier paragraphe après "Attention" par :
```Le mauvais état du véhicule (pneus lisses, rétroviseurs cassés ou absents, dysfonctionnement d'un feu, etc.), l'absence ou la non-validité d'un des documents exigés ci-dessus, pour le candidat ou l'accompagnateur, entraîne le report de l'examen à une date ultérieure.```

- [x] Remplacer le deuxième paragraphe après "Attention" par : 
```Si besoin, vous avez la possibilité d'annuler ou modifier votre réservation. Si vous annulez ou modifiez 7 jours avant la date prévue, vous pourrez librement choisir un autre créneau disponible. Si vous annulez ou modifiez à moins de 7 jours de la date prévue, un délai de repassage de 45 jours à partir de la date de réservation annulée ou modifiée, vous sera appliqué. Nous vous souhaitons une bonne préparation et le succès à l'examen. Pour toute information, vous pouvez consulter notre aide en ligne.```

**Comment by baudointran** [comment]
"7 jours" est remplacé par "${config.daysForbidCancel} jours". ${config.daysForbidCancel} est une variable utlisé dans l'application qui représentant le nombre de jours dont l'annulation n'est pas autorisé.
"45 jours" est remplacé par "${config.timeoutToRetry} jours". ${config.timeoutToRetry} est une variable

**Comment by baudointran** [comment]
@Evbern: J'ai retiré "à BOBGNY" avant la date de réservation, sinon le nom du centre apparaît 2 fois dans la même phrase.
![image](https://user-images.githubusercontent.com/16351036/55168295-df8a1180-5172-11e9-993f-a695d3906487.png)

**Comment by Evbern** [comment]
> @Evbern: J'ai retiré "à BOBGNY" avant la date de réservation, sinon le nom du centre apparaît 2 fois dans la même phrase.

Ok top. Merci @baudointran

**Comment by Evbern** [comment]
@laruiss OK pour moi
