### ISSUE TITLE
Wording de la pop-up d'annulation

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#213]
Proposition
- [x] Sur la pop-in post-annulation, remplacer "Confirmer la suppression" par "Confirmer l'annulation"

- [x] Afficher le bon texte dans le corps de la pop-in
Cas sans pénalité : 
```En poursuivant, votre réservation du [date et heure] sera annulée. Souhaitez-vous confirmer ?```
Cas avec pénalité : 
```En poursuivant, votre réservation du _date et créneau initialement réservés_ sera annulée. De plus, étant à moins de X jours de la date d'examen, un délai de repassage de 45 jours s'appliquera à partir de la date de votre réservation annulée. Souhaitez-vous confirmer ?```

**Comment by laruiss** [comment]
@Evbern Je t'ai assigné la tâche parce qu'on a besoin du texte à ajouter dans la pop-in.

**Comment by Evbern** [comment]
Le texte a été complété

**Comment by Evbern** [comment]
@laruiss @jclaudan le texte de la phrase "En poursuivant …" n'est pas le bon pour les deux cas (sans pénalité et avec pénalité). La suite est OK.

**Comment by Evbern** [comment]
OK @laruiss
