### ISSUE TITLE
Mail d'annulation de réservation : améliorations

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#214]
Propositions : 
- [x] Remplacer le titre du mail "Annulation de Convocation à l'examen" par "Annulation de votre convocation à l'examen"
- [x] Ajouter la date et le créneau de la réservation qui vient d'être annulée
- [x] Ajouter un lien vers la réservation de candilib

**Comment by baudointran** [comment]
@Evbern : Confirmation pour le nouveau mail d'annulation 
![image](https://user-images.githubusercontent.com/16351036/55347517-631a6a00-54b5-11e9-8379-2c0c2b05e7f6.png)

**Comment by Evbern** [comment]
@baudointran 

OK ! Merci

**Comment by Evbern** [comment]
@laruiss OK
