### ISSUE TITLE
Page "Mon profil" : champs tronquées sur mobile

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#215]
Anomalie : 
- [x] Sur les versions mobiles, en affichage vertical, les informations trop longues (ex : l'adresse "10 rue Gutenberg 93420 Vil") sont tronquées sur la page "Mon profil"

**Comment by laruiss** [comment]
Il faut passer les champs `v-textfield` en `p` et styler un peu et ça sera bon.

**Comment by jclaudan** [comment]
fix with #215

**Comment by Evbern** [comment]
@laruiss Ok pour moi
