### ISSUE TITLE
Confirmation de réservation : anomalie

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#220]
- [x] Affichage de "RECAP_RESERVATION_CONFIRMéE"
- [x] Affichage en dessous de "recap_reservation_email_confirmée candilib.box-0@yahoo.com

**Comment by laruiss** [comment]
Ce n'est pas très clair

**Comment by Evbern** [comment]
![DSR - Candilib v2 ano 229](https://user-images.githubusercontent.com/48919541/55073849-1981e780-508f-11e9-956d-430b17feb4a5.png)

**Comment by jclaudan** [comment]
Fix with #221

**Comment by Evbern** [comment]
@laruiss OK pour moi
