### ISSUE TITLE
Date tronquée sur mobile

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#233]
- [x] ETC après avoir choisi le centre, je vois les dates en entier, même en mobile portrait

**Comment by laruiss** [comment]
- [ ] ETC après avoir choisi le centre, je vois les dates en entier, même en mobile portrait

**Comment by jclaudan** [comment]
Problème liée au zoom du navigateur en mode smartphone, cella ne se produira pas sur un réel smartphone

**Comment by Evbern** [comment]
@laruiss OK
