### ISSUE TITLE
Mettre en page le mail de convocation

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#234]
- [ ] ETC je reçois un mail avec beaucoup d'informations, et le mail doit être agréable à lire.

**Comment by laruiss** [comment]
@baudointran @jclaudan @Evbern Est-ce qu'on peut fermer ce ticket ?

**Comment by Evbern** [comment]
@laruiss oui. On fera des ajustements si besoin en fonction du retour des utilisateurs
