### ISSUE TITLE
Prévenir directement le candidat de la pénalité lors d'une modification à moins de 7 jours

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#235]
ETC (à préciser par @philippeBron)

**Comment by philippeBron** [comment]
En tant que candidat, j'ai déjà effectué une réservation pour le 1er avril 14h30 à Saint-Brice, mais je souhaite changer de jour car je ne me sens pas prêt. Nous sommes le 29 mars et je me connecte sur le site candilib pour faire cette opération. Dans la page de ma réservation courante pour le 1er avril, je clique sur le bouton modifier.
Un message s'affiche alors :
"Vous allez changer de date pour votre examen à l'épreuve pratique. Conformément aux règles de gestion de candilib vous ne pourrez pas choisir une nouvelle date avant un délai de 45 jours après le 1er avril. Souhaitez-vous néanmoins poursuivre votre modification ?"

Je confirme mon choix de changer de date d'examen. Je suis alors dirigé vers le processus de choix de centre et de dates comme pour ma première réservation mais ne vois que les places d'examen libres après le 15 mai.

Je sélectionne la date du 22 mai à 13h30 à Saint-Brice. Deux options sont possibles :
* Je confirme ma réservation du 1er avril qui est annulé et remplacée par celle du 22 mai. Je reçois un mail m'indiquant que ma réservation du 1er avril 14h30 à Saint-Brice a été annulée et remplacée par une réservation pour le 22 mai 13h30 à Saint-Brice.
* Finalement je préfère conserver ma réservation du 1er avril et annule mon choix du 22 mai.

Cas d'acception

- [ ] sur la page de rappel de ma date d'examen j'ai un bouton annuler qui affiche le message "Vous allez changer de date pour votre examen à l'épreuve pratique. Conformément aux règles de gestion de candilib vous ne pourrez pas choisir une nouvelle date avant un délai de 45 jours après le 1er avril. Souhaitez-vous néanmoins poursuivre votre modification ?" lorsqu'il est cliqué
- [ ] si je n'accepte pas la pénalité le message s'efface et je suis de nouveau sur la page de rappel de ma réservation sans aucun impact.
- [ ] si je confirme mon choix de changer de date, je suis dirigé vers la page de sélection d'un centre d'examen et entre dans le tunnel de sélection classique
- [ ] dans les places disponibles qui me sont proposées, je ne vois que celle qui sont situées 45 jours après la date de l'examen que je souhaite modifier
- [ ] sur la page de confirmation du choix d'une date d'examen, je peux changer d'avis et annuler mon changement de date. Dans ce cas, je suis redirigé vers la page de rappel de ma date d'examen inchangée
- [ ] sur la page de confirmation du choix d'une date d'examen, je confirme mon choix de nouvelle date. Je suis redirigé vers la page de synthèse de ma réservation avec la nouvelle date sélectionnée
- [ ] si j'ai confirmé mon choix, je reçois un mail m'indiquant que ma précédente réservation est annulée et remplacée par la nouvelle date choisie. Ce mail fait office de nouvelle convocation.
