### ISSUE TITLE
Ajouter les contacts des administrations à prévenir dans la FAQ

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#236]
- [ ] dans la partie "Est-ce que je peux modifier ou annuler mon rendez-vous" il convient d'ajouter les contacts des administrations à prévenir en cas d'empêchement sous forme de liste, pour les départements ayant accès à Candilib

**Comment by Evbern** [comment]
@laruiss peux-tu stp ajouter Fred à l'équipe pour l'assigner à cette issue ? Merci :)

**Comment by Evbern** [comment]
@philippeBron peux-tu stp ajouter Fred à l'équipe pour l'assigner à cette issue ? Merci :)

**Comment by laruiss** [comment]
@philippeBron Fred, Amandine et JP ne sont tjs pas dans les collaborateurs, je pense que ce serait bien, au moins pour Fred
