### ISSUE TITLE
Afficher un message au candidat après un échec à l'examen ou après annulation trop récente

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#240]
Remarque : Actuellement, nous n'avons pas les moyens de détecter les non-admissibles

Affichage du message pour un échec:
- [x] Appliquer aux candidats qui ont échoué après  -45 jours ou récent
- [x] Ne pas Appliquer aux candidats qui ont échoué après  -45 jours ou récent et qui a annulé récemment
       (Cas : Le candidat passe son examen avant sa réservation et échoue et ensuite annule sa réservation )

Affichage du message pour un annulation:
- [x] Appliquer aux candidats qui a une pénalité en cours 
- [x] Appliquer aux candidats qui ont échoué après  -45 jours ou récent et qui a annulé récemment

Le message pour un échec:
Vous avez échoué ou n'avez pas été admissible à l'examen pratique du permis le _date d'échec ou de non admission Aurige_. Un délai de repassage de 45 jours s'appliquant à partir de cette date, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.

Le message pour une annulation trop récent :
Vous avez annulé votre réservation à moins de X jours de l'examen. Un délai de repassage de 45 jours s'appliquant à partir de la date de l'examen annulé, vous pourrez réserver un créneau à partir du _date à partir de laquelle le candidat peut repasser un examen_.
 
Associé #168
Associé #169

**Comment by philippeBron** [comment]
Il me semble qu'il y a deux cas distincts incompatibles.
L'échec se détecte lors de la synchronisation sans que le candidat soit connecté. Si on doit l'informer, cela ne peut se faire que par mail.
L'annulation en revanche est le résultat d'une action du candidat qui peut donc être alerté via un message sur l'interface sur laquelle il interagit.

**Comment by philippeBron** [comment]
de plus le cas d'usage d'annulation trop récente est décrit dans l'issue #235

**Comment by baudointran** [comment]
Proposition : Réunir les 2 messages

Suite à votre réservation pour passer l'examen pratique du ..... vous ne pouvez pas prendre de nouveau rendez-vous avant le ..... conformément à l'application du délai de 45 jours décrit dans les conditions d'utilisation

@Evbern : Est-ce tu valide cette idée?

**Comment by Evbern** [comment]
@philippeBron 
Ok pour le prévenir par mail qd il a échoué puis avec un message dans l'application

@baudointran 
Ok pour cette idée : 1 message commun relatif à l'application du délai de 45 jours. Mais il faudrait un lien hypertexte permettant d'accès aux conditions d'utilisation en cliquant sur "les conditions d'utilisation".

Merci :)

**Comment by laruiss** [comment]
Qu'est-ce que tu appelles "Les conditions d'utilisation ?". Parce que ça n'existe pas actuellement, à ma connaissance.

**Comment by Evbern** [comment]
@laruiss 
Il n'y a pas de page "conditions d'utilisation". Je propose qu'on remplace : "les conditions d'utilisation" par "la FAQ" (il faudrait que le lien hypertexte renvoie à la partie de la FAQ qui décrit la règle des 45 jours).
