### ISSUE TITLE
Le template de mail pour suppression de reservation par le synchro aurige

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#244]
Voici le template de mail à valider ou modifier

M/Mme [client], 
En raison de l’application de la réglementation relative au délai imposé entre 2 passages de l’examen, votre réservation à l'examen pratique du permis de conduire à [location] le [date_start] à [time_start] avec le numéro NEPH [data_field_2] est malheureusement annulée. 

Nous vous invitons à vous positionner sur un nouveau créneau.
Pour toute information, vous pouvez consulter notre aide en ligne.

L'équipe Candilib

**Comment by Evbern** [comment]
@baudointran OK pour moi (avec les liens renvoyant vers les pages dédiées de Candilib pour "nouveau créneau" et "notre aide en ligne)
