### ISSUE TITLE
Afficher des informations de remplissage des centres sur ma page d'accueil

### ISSUE THREAD

**Issue by Fredsr** [LAB-MI/candilibV2#250]
ETA, sur la page d'accueil je vois  

- [x] les centres du département actif (si plusieurs, prendre le premier de sa liste -de 2- par défaut)

- [x] pour chaque centre, je vois le ratio places offertes/places réservées pour chaque semaine programmée, c'est à dire ceux pour lesquels un planning a été chargé (4 sites au maximum peuvent faire du candidat libre)

- un ensemble de lien :
  - [x] un qui amène aux plannings des IPCSR pour le jour même, et qui a pour label 
    `Gestion des plannings des IPCSR` avec une icône de calendrier
  - [ ] un qui amène à la gestion des candidats, et qui a pour label 
    `Gestion des candidats` avec une icône à définir

**Comment by heydine** [comment]
- [ ] Possibilité de télécharger ou visualiser les réservations passées (date examen, heure, ipcsr, nom candidat, neph), afin de tenir des stats à jour si pas encore de stat précise dans la V2 (voir avec Fred et cap gemini).

**Comment by jpfialeix** [comment]
test

**Comment by Evbern** [comment]
![DSR - Candilib admin accueil](https://user-images.githubusercontent.com/48919541/55814316-8913c000-5aee-11e9-84c3-95c7062c974b.jpg)

**Comment by Evbern** [comment]
![image](https://user-images.githubusercontent.com/48919541/55871143-51f2ec80-5b8a-11e9-9cc1-98dcbff23055.png)

**Comment by jpfialeix** [comment]
Je verrais plutôt à l'envers, c'est à dire la semaine en haut et le % en bas.
Par ailleurs, il faut que ce soit les mêmes semaines sur tous les centres en prévoyant que sur une semaine il puisse n'y avoir aucune place offerte sur un centre. Dans ce cas, pas de % mais vide ou 0/0 ou autre...

**Comment by laruiss** [comment]
Il n'y a plus de page de gestion de candidat. Je ferme donc ce ticket.
