### ISSUE TITLE
Afficher un bandeau transverse

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#261]
ETA, je visualise sur toutes les pages : 

- [x] le menu : accueil, gestion du planning, gestion des candidats 

- [ ] mon nom, prénom

- [x] mon département

- [x] la liste déroulante / ou hexagones de mes autres départements (quand gestion de n départements (max 2) ou admin)

**Comment by Evbern** [comment]
![image](https://user-images.githubusercontent.com/48919541/55871171-646d2600-5b8a-11e9-9083-afbbaaa08df0.png)

**Comment by laruiss** [comment]
Nous n'avons pas le prénom des inspecteurs, seulement le nom. Aujourd'hui on affiche l'email. Est-ce qu'on peut fermer ce ticket ? Éventuellement en ouvrir un autre quand il sera décidé quoi afficher au centre du bandeau ?

**Comment by Evbern** [comment]
@laruiss OK
