### ISSUE TITLE
Archiver les places des candidats qui ont réussi l'examen (lors de la synchro Aurige)

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#265]
- [x] Archivage de la réservation

Dépend d'une modification du retour Aurige pour savoir si le candidat a réussi en tant que candidat libre ou par l'intermédiaire d'une auto-école

**Comment by philippeBron** [comment]
Pourquoi la réussite entant que candidat libre ou entant que élève d'une auto-école est-elle importante dans l'archivage ?
Est-ce prioritaire pour la sortie de la v2.0 ?
