### ISSUE TITLE
Préciser la signification des * dans confirmation réservation

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#281]
Les labels des deux cases à cocher comportent des * à la fin.
Préciser que ces cases doivent être obligatoirement cochées pour pouvoir valider le formulaires de réservation.

**Comment by philippeBron** [comment]
Je propose la formulation suivante :
Confirmez en cochant obligatoirement les deux cases suivantes
- [ ] qu’une voiture à double commande est disponible
- [ ] qu’une personne peut vous accompagner

**Comment by Evbern** [comment]
OK !
