### ISSUE TITLE
Impossible d'ajouter un centre ayant le même matricule dans 2 départements différents

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#282]
Le contrôle de doublon lors de l'initialisation via dev-setup se fait sur le matricule du centre.
De même, le nom du centre est défini comme un index de la collection Mongo "centres".

C'est deux élément ne permettent pas d'avoir deux centres de même nom bien qu'étant dans des départements différents.

**Comment by baudointran** [comment]
@Evbern 
Les centres ont-ils des matricules ?

**Comment by Evbern** [comment]
@baudointran 
Comme échangé, pas de matricule (car unicité du couple nom x département)
