### ISSUE TITLE
Prévoir un profil super administrateur

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#286]
Avec les fonctionnalités suivantes exclusives
- [x] Une liste déroulante pour naviguer d'un département à l'autre
- [x] Un bouton pour lancer les validations Aurige (cf. validation Aurige)
- [x] Indicateurs nationaux

**Comment by laruiss** [comment]
Doit être découpé en plusieurs tickets

**Comment by baudointran** [comment]
il y a 2 profiles super administrateur : 
- admin 
- tech: durée de vie est 1h

**Comment by Carolinedanslesnuages** [comment]
@Evbern @laruiss @baudointran  
Hello, Ce ticket n'est-il pas résolu ?

**Comment by Evbern** [comment]
Hello, pour moi c'est outdated. On peut fermer selon moi.

**Comment by Carolinedanslesnuages** [comment]
Merci @Evbern
