### ISSUE TITLE
Constituer le référentiel des inspecteurs via les csv

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#289]
- [ ] Le référentiel des inspecteurs est enrichi au fil des chargements csv
- [ ] La donnée maître est celle du dernier fichier csv
- [ ] L'identifiant unique de l'inspecteur qui sert de clé est son matricule

**Comment by baudointran** [comment]
@Evbern @laruiss @jclaudan @Carolinedanslesnuages 
Dans le même fichier CSV, s'il y a 2 inspecteurs avec le même matricule que doit-on faire?
- modifier le référentiel avec la dernier ligne saisie 
- Ou on informe l'admin qu'il y a une incohérence et on fait de ne pas de traitement sur cette ligne

**Comment by Evbern** [comment]
@baudointran @Fredsr @laruiss @Carolinedanslesnuages 
Je propose qu'on modifie le référentiel avec la dernière ligne saisie pour ne pas bloquer le chargement (ce cas risque d'arriver pour un même inspecteur mais orthographié différemment par maladresse => impact métier limité).

**Comment by laruiss** [comment]
Où est-ce qu'on en est ?

**Comment by Evbern** [comment]
@laruiss @baudointran 
Option 2 finalement : on informe qu'il y a une incohérence et on ne fait pas le traitement de la ligne

**Comment by baudointran** [comment]
@Evbern 
Le fichier de chargement des place ne contient pas les adresses mails,
- Si l'e-mail de l'inspecteur est manquant, que fait-on? On ne crée pas l'inspecteur donc pas de place ou on crée l'inspecteur sans e-mail donc pas d'envoi de bordereau. 
- Si l'e-mail est différent, doit-on mettre à jours l'e-mail de l'inspecteur? Si oui, donc la dernier ligne contenant l'e-mail est prise en compte.

**Comment by Evbern** [comment]
@baudointran 

Le référentiel des IPCSR contient les adresses mails, noms et matricules. Je propose donc :
- qu'on constitue un référentiel des IPCSR par département à la main (par une admin centrale)
- que le chargement des CSV de chargement du planning ne constitue, ni complète le référentiel
- qu'on ne rajoute pas l'adresse email de l'IPCSR dans les CSV de chargement du planning
- que toute incohérence dans le chargement du CSV (IPCSR inconnu, couple matricule x nom inconnu) entraine un non-traitement de la ligne en informant qu'il y a une incohérence

Je valide le closing de l'issue avec Fred

**Comment by pli01** [comment]
Le format actuel utilisé pour le chargement des referentiels des inspecteurs IDF+69 (en CSV,JSON) est de la forme:

```
matricule,NOM,Prénom,adresse mail,département
```
Format JSON
```
{
    "departement": "75",
    "nom": "DUPOND",
    "email": "inspecteur1@mail.example.com",
    "matricule": "01234",
    "prenom": "Bob"
}
```

**Comment by baudointran** [comment]
Plus d'actualité, sur version v2.5.0, ce sont les départiteurs et le délégué du département qui gèrent les inspecteurs de leur appartement
