### ISSUE TITLE
Constituer le référentiel des centres via un réferentiel mis à jour manuellement

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#292]
Transmission du référentiel par Frédéric (IDF + 69)
- [ ] La clé sera le couple Nom x ID du centre transmis

**Comment by baudointran** [comment]
En format CSV ou JSON
Les champs que nous avons besoin sont:
- departement
- nom
- adresse

exemple en json:
 {
    "departement": "93",
    "nom": "Rosny",
    "adresse": "99 Avenue du Général de Gaulle, Rosny ss Bois, FR, 93110"
  }

**Comment by laruiss** [comment]
Où en est-on, de ça ? Je croyais que finalement l'identifiant était le nom ?

**Comment by Evbern** [comment]
@laruiss @baudointran 

Chaque centre disposant d'un ID Aurige, on devrait les identifier via le couple Nom / ID.
C'est le cas aujourd'hui dans Candilib ?

**Comment by pli01** [comment]
Le referentiel actuellement utilisé (CSV) pour IDF+69 est de la forme:
```
Nom du centre ,ID Aurige du centre ,adresse,code postal,ville,département (format numérique),coordonnées GPS
```
