### ISSUE TITLE
Annuler ma reservation

### ISSUE THREAD

**Issue by Carolinedanslesnuages** [LAB-MI/candilibV2#325]
Lorsque je souhaite annuler ma réservation un message d'erreur s'affiche:
![Capture d’écran de 2019-05-16 14-11-56](https://user-images.githubusercontent.com/45307611/57852906-b0903380-77e4-11e9-8a7a-e9b1871bfdcf.png)

**Comment by laruiss** [comment]
@jclaudan Tu voudrais bien regarder ça ?
