### ISSUE TITLE
Afficher les tableaux en page d'accueil

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#327]
ETD, lorsque je me connecte, la page d'accueil n'affiche pas systématiquement les tableaux présentant les Places disponibles / Total places.

Les tableaux s'affichent uniquement si je change de page dans Candilib puis reviens en page d'accueil.

**Comment by laruiss** [comment]
Est-ce que c'est encore le cas ?

**Comment by Evbern** [comment]
Non reproduit de mon côté, je close @laruiss
