### ISSUE TITLE
Gérer des pénalités pour les candidats absents, non recevables et non examinables (à voir avec Fred)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#340]
Il convient de mettre en place des pénalités pour les candidats en fonction de leur statut à l'examen 
- [ ] Absents = X jours
- [ ] Non recevables = X jours 
- [ ] Non examinables = X jours

**Comment by baudointran** [comment]
@Evbern Il me faudrai plus d'explications ou de descriptions sur cette 'issue'

**Comment by Evbern** [comment]
@baudointran oui nous allons creuser le sujet avec Fred et détailler l'issue asap
