### ISSUE TITLE
Lien pour valider l'adresse email non fonctionnel (env. "en ligne")

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#350]
ETC, lorsque je clique sur le lien " Valider mon adresse email " dans le mail " Validation d'adresse email pour Candilib", la page est introuvable.

**Comment by Evbern** [comment]
Mail
![image](https://user-images.githubusercontent.com/48919541/58260018-041af800-7d76-11e9-8636-afae87d8ad21.png)

Page introuvable
![image](https://user-images.githubusercontent.com/48919541/58260077-1ac14f00-7d76-11e9-9cbd-ca5c1b446364.png)

**Comment by baudointran** [comment]
@pli01 
Il y a un double / dans le lien de "Valider mon adresse email" ( https://beta.interieur.gouv.fr//candilibV2/....)
Il y a peut-être une erreur dans la variable PUBLIC_URL

**Comment by pli01** [comment]
Configuration corrigée

**Comment by Evbern** [comment]
@pli01 Oui tout est OK :)

**Comment by Evbern** [comment]
![image](https://user-images.githubusercontent.com/48919541/58407938-11353100-806d-11e9-9e10-cb526e8c8ba3.png)
