### ISSUE TITLE
Préciser les boutons d'actions sur la confirmation de résa (candidat)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#361]
ETC, je souhaite annuler ou modifier ma réservation ou renvoyer ma confirmation.
Il faudrait expliciter les boutons :
- [x] Annuler => Annuler ma réservation
- [x] Modifier => Modifier ma réservation
- [x] Renvoyer => Renvoyer ma convocation ?

**Comment by philippeBron** [comment]
done PR #391
