### ISSUE TITLE
Gérer "Erreur de fetch" lors du chargement avec erreur

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#374]
ETD, lorsque j'accède au planning détaillé et que je souhaite naviguer d'un centre à l'autre, un message en rouge apparaît parfois en bas de la page, suite à une longue période de chargement : "Erreur de fetch"

**Comment by Evbern** [comment]
ETD, lorsque j'accède au planning détaillée et que je souhaite naviguer d'un centre à l'autre, un message en rouge apparaît parfois en bas de le page, suite à une longue période de chargement : "Erreur de fetch"

**Comment by baudointran** [comment]
Impossible de reproduire l'affichage du message
