### ISSUE TITLE
Ajuster FAQ et Messages (cf. mail 2905)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#383]

**Comment by laruiss** [comment]
Il faudrait avoir toutes les informations ici, sauf si c'est sensible, mais je ne crois pas que ce soit le cas, si ?

**Comment by Evbern** [comment]
[Modif FAQ V2.pdf](https://github.com/LAB-MI/candilibV2/files/3257832/Modif.FAQ.V2.pdf)

**Comment by Evbern** [comment]
@laruiss C'est déposé
