### ISSUE TITLE
Nouvelles RG suite à la màj batch Aurige

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#399]
ETC, je souhaite m'inscrire à la plateforme. Une fois pré-inscrit, des contrôles sont effectués avec des données Aurige pour valider mon éligibilité à m'inscrire à l'épreuve pratique.

L'enrichissement du batch Aurige implique la séquence de contrôles suivante.

- [x] 1 | candidatExistant ?
       - NOK ou NOK nom : message candidat non trouvé
       - OK : étape suivante

- [x] 2 | dateReussiteETG : Champ vide ?
         - OK : message ETG invalide existant
         - NOK : étape suivante

- [x] 3 | dateReussiteETG > 5 ans ?
          - OK message ETG invalide existant
          - NOK : étape suivante

- [x] 4 | nbEchecsPratiques > 4 ? **(new)**
         - OK : message ETG invalide existant
         - NOK : étape suivante

- [x] 5 | reussitePratique : Champ vide ?
         - OK : inscription validée
         - NOK : message inscription invalidée car réussite pratique

**Comment by baudointran** [comment]
@Evbern 
Pour '4 | nbEchecsPratiques > 4 ? (new)', Quel est le texte du mail à envoyer au candidat?

**Comment by Evbern** [comment]
@baudointran pour l'instant le même message que celui utilisé pour l'ETG non valide. Je vais mettre le message dans une autre issue à planifier ultérieurement.

**Comment by baudointran** [comment]
[ ] : 4 | nbEchecsPratiques > 4 ? (new)
- OK : message ETG invalide existant
- NOK : étape suivante
- Si le candidat possède une réservation et l'échec est à la date de cette réservation, elle sera supprimer et archivé 
- Si le candidate possède une réservation et l'échec est à une autre date, la place sera liberé
