### ISSUE TITLE
Automatiser et personnaliser l'envoi des bordereaux

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#400]
ETD, je souhaite disposer d'un envoi **automatique** et **manuel** des bordereaux aux IPCSR.

- [x] Je peux demander de recevoir par mail tous les bordereaux dans le corps de mail des inspecteurs d'un département pour une date que je choisis (cf. issue 259)

**Comment by laruiss** [comment]
Si un inspecteur n'a pas d'examen à faire passer le jour choisi, est-ce qu'un email doit lui être envoyé ? Si oui, avec quel message ?

**Comment by Evbern** [comment]
Si un inspecteur n'a pas d'examen à faire passer le jour choisi, il ne faut pas lui envoyer de mail.

**Comment by baudointran** [comment]
@Evbern : Si l'envoi automatique des bordereaux a échoué, 
 Doit-on envoyer une email d’échec d'envoi aux répartiteurs ou délégués ?
 A qui doit-on envoyer l'email d’échec d'envoi?
 Doit-on relancer l'envoi automatique?

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/60023963-2b2b5900-9697-11e9-930d-641f154aa834.png)

**Comment by Evbern** [comment]
Ok pour Baudoin pour ce fonctionnement :
- envoi d’un mail à l’adresse générique du département associé aux centres
- envoi du même message d’erreur que celui prévu pour l’échec d’envoi manuel des bordereaux (je vous le transmets dans la matinée)
