### ISSUE TITLE
Rapport incomplet lors du chargement du planning

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#404]
ETD, je charge le csv contenant les colonnes suivantes : Date,Heure,Matricule,Nom,Centre,Departement

Suite à la mise dernière à jour du format du CSV (remplacement de la colonne "Inspecteur" par "Matricule" et ajout de la colonne "Nom" après la colonne "Matricule"), le rapport n'apparaît pas.

**Comment by laruiss** [comment]
Je n'ai pas constaté le bug, vous l'avez toujours ?

**Comment by Evbern** [comment]
,,,
Date,Heure,Matricule,Nom,Centre,Departement
16/07/19,08:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,08:30,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,09:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,09:30,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,10:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,10:30,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,11:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,11:30,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,12:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,12:30,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,13:00,7501020301,DUPONDDU75,VILLACOUBLAY,75
16/07/19,13:00,7501020301,DUPONDDU75,ROSNY/PARIS,75
16/07/19,13:00,7501001,DUPOND102,ROSNY/PARIS,75

Avant dernière ligne : IPCSR déjà planifié à VILLACOUBLAY sur le même horaire
Dernière ligne : IPCSR n'existe pas

Or aucune erreur n'apparait dans le rapport @laruiss

**Comment by laruiss** [comment]
@jclaudan Tu veux bien regarder ça, s'il te plaît ?
