### ISSUE TITLE
Afficher plus d'info lors de la recherche de candidats

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#409]
ETD, je dispose d'une barre de recherche alphabétique et numérique pour rechercher un candidat par son nom, prénom, neph, email

Dans la page de réponse, je veux pouvoir accéder à toutes les infos du candidat par ordre chronologique de ses actions, en particulier les informations suivantes

- [ ] modification, date de modif et de la nouvelle résa, horaires, centre, ipcsr

- [x] annulation, date

- [x] toute information liée au batch Aurige, examen réussi, modification de son profil SNPC ...

**Comment by Carolinedanslesnuages** [comment]
@Evbern : En l'état, nous n'archivons pas lorsque l'admin modifie un créneau vers un autre créneau, ni lorsque l'on change l'inspecteur cela ne peux pas faire partie de l'historique des actions pour le moment.

**Comment by Evbern** [comment]
Ok. Je ferme cette issue et en crée une autre pour plus tard avec l'archivage détaillé des modifs.
