### ISSUE TITLE
Ajouter un Request-ID (candidat ou repartiteur) dans la journalisation des actions effectuées sur l'application 

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#432]
Suivre le parcours (candidat ou répartiteur) dans l'application, afin de pouvoir diagnostiquer, tracer ou mesurer les temps de réponses.
Ceci se traduit par l'ajout dans les journaux de l'application (nginx, api), d'un champs "request-id" unique par client.

**Comment by pli01** [comment]
Les logs nginx, api http, api app: doivent contenir un champs "request_id", propagé au navigateur et à l'api par le biais de header HTTP "X-Request-Id" :
```
# logs nginx json
{ "nginx": { ....,  "request_id": "7f75b81cec7ae4a1d70411fefe5a6ace", ...}}
```
```
# logs  HTTP api json
{ "api": {...,  "request_id": "7f75b81cec7ae4a1d70411fefe5a6ace", ...}}
```
```
# logs  app  api json
{"content":{..},"meta":{"request_id": "7f75b81cec7ae4a1d70411fefe5a6ace"}}
```

**Comment by pli01** [comment]
Conf nginx: https://www.nginx.com/blog/application-tracing-nginx-plus/
Nodejs: https://devcenter.heroku.com/articles/http-request-id#usage-with-node-js

**Comment by pli01** [comment]
PR  #449

**Comment by baudointran** [comment]
Manque le mettre à jours la configuration nginx pour propager le X-REQUEST-ID
