### ISSUE TITLE
Faire pointer OSM sur la géoloc du centre à partir du lien de la page "Récapitulation"

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#453]
Actuellement, le pointeur géoloc de la liste des centres amène bien à la bonne adresse avec le marqueur sur OpenStreetMap (OSM), mais pas sur la page de récap de la réservation :

![Pointeur-non-fonctionnel](https://user-images.githubusercontent.com/2486424/59425075-862a9980-8dd5-11e9-9317-015e953c8358.png)

Il faut donc ajouter le bon lien sur le pointeur.

**Comment by Evbern** [comment]
OK
