### ISSUE TITLE
cas non réussite hors candilib : pas d'archivage de la place en EXAM_FAILED

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#505]
Lorsqu'un candidat est en non réussite sur un examen pratique, et que la date de passage ne correspond pas à sa date de réservation, il ne faut pas archiver sa place avec la mention *"EXAM_FAILED"*.
Cette mention est réservée pour les candidat ayant passé l'épreuve via une réservation candilib.

Proposition : utiliser la mention *"EXAM_FAILED_NCANDILIB"*

**Comment by pli01** [comment]
ok
