### ISSUE TITLE
Ajuster l'organisation de la FAQ

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#518]
ETC, lorsque je consulte la FAQ, je trouve l'information suivante 
"Si vous avez échoué, avez été refusé par l’inspecteur ou avez été absent à l'examen pratique du permis de conduire, il vous sera automatiquement appliqué une pénalité de 45 jours de délais avant de pouvoir effectuer une nouvelle réservation." dans la rubrique "est-ce que je peux annuler..." 

Il faudrait
- [x] Créer une rubrique "je n'ai pas réussi mon examen, puis-je reprendre une place ?" à la suite de la rubrique "est-ce que je peux annuler..." 
- [x] Retirer le texte ci-dessus de la rubrique "est-ce que je peux annuler" et la mettre dans la nouvelle rubrique créée

**Comment by pli01** [comment]
ok
