### ISSUE TITLE
Envoyer les bordereaux aux inspecteurs du département

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#536]
ETD, je souhaite disposer d'un envoi **manuel** des bordereaux aux IPCSR de mon département.

- [x] Je peux demander d'envoyer par mail tous les bordereaux dans le corps de mail des inspecteurs d'un département pour une date que je choisis, via un bouton "Envoyer les bordereaux aux inspecteurs du 93" à côté de l'actuel bouton "Générer les bordereaux inspecteurs du 93"

**Comment by pli01** [comment]
Ok en qualif
