### ISSUE TITLE
Enrichir la FAQ

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#539]
ETC, je peux accéder à la FAQ sur Candilib. Il convient de la compléter comme suit :

- [x] Ajouter les contacts des admins départementales
_Message à rédiger_

**Comment by jpfialeix** [comment]
C'est quoi le message envisagé concernant une annulation à 48 h ? 48 h ???

**Comment by baudointran** [comment]
Mise à jours des conctats candilib

**Comment by Evbern** [comment]
Associée à la #236
