### ISSUE TITLE
Enrichir les mails (RGPD)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#540]
ETC, je peux être informé par des mails tout au long de mon parcours dans Candilib. Il convient d'en ajuster comme suit :

- [ ] Ajouter dans les mails le fait que les décisions ont été réalisées par un algorithme (pour conformité RGPD)
_Message : cf. grooming_

- [ ] Modifier le mail de rejet Nok-Nom, ajouter le fait de contacter l’admin départementale concernée
_Message : cf. grooming_

**Comment by jpfialeix** [comment]
Pour les rejets des NOK-NOM, il faudra d'abord inviter le candidat à bien revérifier intégralement ce qu'il a saisi. L'"administration départementale" n'a pas vocation à venir au secours de quelqu'un qui met son n° de téléphone à la place de son NEPH ou son prénom dans nom de naissance.

**Comment by jclaudan** [comment]
à groomer lundi

**Comment by jpfialeix** [comment]
Ça me semble inconcevable qu'il y ait quelqu'un de chez nous lundi. 
Amandine sera totalement seule lundi, sans répartiteur 93 (et sans moi).

Peut-être par téléphone ?

Email Signature
logo DRIEA

	
Jean-Pierre FIALEIX
Chef de la cellule Répartition / BEPECASER
Pôle Méthode Éducation Routière•Service Circulation, Éducation et 
Sécurité Routières•Unité Départementale de la Seine-Saint-Denis
téléphone 01.41.60.69.91
direction régionale et interdépartementale de l'équipement et de 
l'aménagement
adresse7 esplanade Jean-Moulin - BP 189 - 93003 BOBIGNY CEDEX
site webdriea.ile-de-france.developpement-durable.gouv.fr 
<http://www.driea.ile-de-france.developpement-durable.gouv.fr> linkedin 
<https://www.linkedin.com/company/driea-ile-de-france/>

Eco-attitudePensez environnement ! N'imprimez ce message que si c'est 
vraiment nécessaire
