### ISSUE TITLE
Ajuster la popup d'évaluation de l'application

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#559]
ETC, lorsque j'évalue l'application, je souhaite pouvoir disposer des ajustements suivants :
- [x] Ajouter "Laissez-nous un commentaire" juste en dessous des étoiles
- [x] Re-afficher la pop-up à la déconnexion si elle n'a pas été complétée à l'issue de la réservation

**Comment by jclaudan** [comment]
Pourquoi retirer le bouton "Plus tard" @Evbern

**Comment by laruiss** [comment]
Hello, je ne trouve pas cohérent de demander à supprimer le bouton "Plus tard", mais de demander à la réafficher... plus tard 🤔 

On en parle lundi ?

**Comment by Evbern** [comment]
@laruiss @jclaudan ok ça me va !

**Comment by Evbern** [comment]
@laruiss @laruiss KO pour le 2e point

J'ai fait une réservation, attendu l'affichage de la popup, cliqué à côté de la popup pour qu'elle disparaisse. Je me suis alors déconnecté et la popup n'est pas apparue.

**Comment by Evbern** [comment]
@laruiss @baudointran @Carolinedanslesnuages 
C'est OK (en cliquant sur "Plus tard" comme en cliquant à côté de la popup avant se déconnecter)
