### ISSUE TITLE
ETC pré-inscription message ''Cannot read property 'departement' of null"

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#563]
ETC lorsque je tente une pré-inscription avec une adresse email qui n'est pas dans la whitelist, j'obtient le message ''Cannot read property 'departement' of null"

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/61793965-72387580-ae20-11e9-9448-fcaf12799fd6.png)

**Comment by philippeBron** [comment]
Message :

> L'adresse courriel renseignée (qskdfo@gmail.com) n'est pas dans la liste des invités.
