### ISSUE TITLE
(1) Dans la vue admin et candidat: Forcer la casse du nom des centres en majuscule

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#574]
Dans la vue admin et candidat: Forcer la casse du nom des centres en majuscule et sans tiret

**Comment by baudointran** [comment]
- Uniformiser la casse de nom  des centres

**Comment by baudointran** [comment]
Le nom des centres seront enregistré en majuscule et il est convertie en majuscule après la réponse des requêtes en base de données

**Comment by Evbern** [comment]
Ok, GO :) !
