### ISSUE TITLE
Modification texte mail annulation administrative

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#577]
Modifier le mail envoyé aux candidats lors d'une annulation administrative.
**Texte actuel :**
Madame, Monsieur XXX,

Votre réservation à Bobigny le mardi 06 août 2019 à 13:30 avec le numéro NEPH 000000000000 a été annulée suite à un imprévu lié à l'administration.
Vous serez contacté dans les prochains jours pour replanifier un créneau à votre convenance.
Vous pouvez aussi solliciter le service administratif dédié dès à présent. 

**Texte corrigé :**
Madame, Monsieur XXX,

Votre réservation à Bobigny le mardi 06 août 2019 à 13:30 avec le numéro NEPH 000000000000 a été annulée suite à un imprévu lié à l'administration.
*Vous pouvez dès à présent replanifier un créneau à votre convenance :  se connecter*
*Veuillez nous excuser pour la gène occasionnée.*

**Remarque :**
La lien "se connecter" n'est pas indispensable dans un premier temps

**Comment by laruiss** [comment]
C'est vraiment pas plus pressé que janvier ?
