### ISSUE TITLE
Mettre à jour les donnees du candidat archivé suite à la màj du batch Aurige

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#593]
Associé a l'issue #399  et #505

Mettre à jour les donnees du candidat archivé, a partir des informations renvoyées par la synchro aurige:
Exemple: "nbEchecsPratiques" = 0 alors qu'il devrait avoir la valeur "5".

**Comment by philippeBron** [comment]
Le nombre d'échec est bien mis à jour mais l'information DateETG n'est pas mise à jour dans les données du candidat archivé.
La valeur de `isValidatedByAurige` devrait être à `true` car le candidat est bien valide mais ne satisfait pas les conditions d'éligibilité (comme un ETG absent ou expiré)

**Comment by Evbern** [comment]
OK, GO :)

**Comment by laruiss** [comment]
@baudointran Est-ce qu'on peut fermer ce ticket ?

**Comment by baudointran** [comment]
Non, il y a un souci de le mise à jours de la date ETG quand le candidat a été déjà validé par synchro-auroge.

**Comment by Evbern** [comment]
@laruiss @baudointran 
C'est OK !
