### ISSUE TITLE
Le titre du sujet du mail envoyé au candidat suite à une réussite à la pratique, est il bien formulé ?

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#594]
Associé à l'issue #472

Le titre du sujet du mail envoyé au candidat suite à une réussite à la pratique, est il bien formulé ?

"Problème inscription Candilib"

**Comment by baudointran** [comment]
Question: Y a-t-il un envoi de courriel pour les candidats qui ont réussi la pratique avec candilib?

**Comment by baudointran** [comment]
Le candidat reçois un résultat incorrect
   - la cause est des erreurs de saisie sur le nom ou le nef ou candidat
   - Il y a une action humain pour la vérification des résultats après l'enregistrement d'Aurige
Le même cas se produit pour les échecs

La solution possible, mais à étudier, est de différer l'envoi des résultats pour laisser le temps de vérifier les résultats saisis. Durant ce laps de temps, le candidat peut modifier ou annuler sa réservation, qui provoque une erreur dans les calculs de nombre de passage avec candilib
