### ISSUE TITLE
(1) Expliciter les messages d'erreur lors du chargement des places

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#595]
ETR, lorsque je charge des places via un fichier CSV ou XLSX avec un format incorrect (colonne absente) le message d'erreur n'est pas explicite. Il convient de les modifier comme suit
- [x] Une colonne est absente du fichier de chargement (rappel des colonnes : date, heure, matricule, nom, centre, departement)

**Comment by baudointran** [comment]
Il faudra vérifier le format du fichier avant de le traiter

**Comment by Evbern** [comment]
OK @laruiss
