### ISSUE TITLE
Planification d'un IPCSR d'un autre département

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#598]
ETR, si je planifie (dans le fichier CSV ou XLSX) un IPCSR d'un autre département que celui de mon périmètre : 
- Un message apparaît lors du chargement "Place enregistrée en base"
- L'IPCSR n'apparaît pas dans le planning du département concerné
- La place affectée au l'IPCSR est comptabilisée dans le Tableau de bord,
- L'IPCSR est néanmoins stocké en base pour le département en erreur, ce qui l'empêche d'être programmé sur son département d'affectation d'origine
En conséquence, dans le département d'origine de l'IPCSR , celui ci ne peut plus être affecté au même créneau

Choix à discuter:
 ~~- [ ] Il convient de ne plus stocker cette planification de l'IPCSR~~
- [ ] Ou bien on autorise ce cas, et Il convient de corriger l'affichage du planning du département

**Comment by baudointran** [comment]
- [ ] Rendre visible les inspecteurs

**Comment by baudointran** [comment]
A vérifier,
