### ISSUE TITLE
ETC je peux accéder à la partie connectée sans être dans la BDD 

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#599]
ETC lorsque je suis supprimé de la BDD mais ai un Token encore valide je peux encore me connecter sans pour autant voir l'interface

**Comment by Evbern** [comment]
@jclaudan sais-tu où en est ce ticket ? Merci

**Comment by Evbern** [comment]
@jclaudan pourquoi as-tu mis en Defect Backlog ?
Cela semble OK pour @baudointran
Merci
