### ISSUE TITLE
Afficher la légende des codes couleurs statistiques

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#600]
ETA, lorsque je consulte les tableaux de bord

- [x] Je souhaite disposer d'une légende expliquant les ratios des 4 codes couleurs de la colonne "Semaine du"
- [x] Cette explication peut être affichée via : un bouton d'information positionné à l'angle droit de chaque tableau de centre

**Comment by laruiss** [comment]
C'est vraiment pas plus pressé que janvier, ça ?

**Comment by Evbern** [comment]
![IMG_7326](https://user-images.githubusercontent.com/48919541/65054743-58259a00-d96e-11e9-86d6-e8e5a768a824.jpg)

**Comment by Evbern** [comment]
@jclaudan
