### ISSUE TITLE
ETR mauvaise incrémentation de date gestion des planning IPCSR   

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#602]
ETR lorsque je sélectionne une date via DatePicker puis j'incrémente le jour la j'obtient une incohérence sur la date.

**Comment by pli01** [comment]
Le comportement demandé fonctionne correctement
[X] Dans "gestion planning" Lorsque je selectionne une date, je peux incrémenter et j'obtiens bien les dates demandées
[ ] Dans "gestion planning" , je dois arriver sur la date courant

En revanche, lorsque je sélectionne le TDB puis/  menu "Gestion Planning", je ne reviens plus à la date de la semaine courante.
