### ISSUE TITLE
ETR, le nom du centre n'est pas correct, lors de l'affectation du candidat à une place depuis le TBD #617

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#616]
ETR,
Lorsque je suis sur le TDB, que je selectionne une date d'un centre, (le 2 eme ou 3eme centre de la liste)
J'affecte un candidat, 
le nom du centre n'est pas correctement affiché dans la fenetre de validation. (le premier centre est affiché à la place)

En revanche, en passant par le Menu "gestion du planning" , si je choisis la date, et le centre, que j'affecte un candidat, la valeur du centre est correctement affiché dans la fenetre de validation

**Comment by jclaudan** [comment]
same #617

**Comment by Evbern** [comment]
OK pour moi en qualif
