### ISSUE TITLE
ETA, Perte de connexion sur firefox 52.5 (à tester jeudi)

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#621]
Après une pause de plusieurs minute, un message Token Invalide apparaît (difficile a reproduire car c'est produit uniquement sur l’environnement de formation)

**Comment by laruiss** [comment]
Est-ce que le problème est toujours d'actualité ?

**Comment by Evbern** [comment]
Pas reproduit de mon côté dernièrement. 
Je prends le point pour mes tests de jeudi.

**Comment by laruiss** [comment]
Tu as pu testé ?
