### ISSUE TITLE
ETR: Changement de département d'un candidat

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#623]
Lorsqu'un candidat passe d'une whiteList à l'autre, (ex: suite a un déménagement), il conserve le département de la première whiteList dans laquelle il a été affecté.

_A groomer avec Fred_

**Comment by pli01** [comment]
Proposition pour le changement de departement d'un candidat:
conserver le fonctionnement actuel et compléter avec

1. ajouter la vérification au moment de l'inscription dans la liste blanche pour voir si il n'y a pas déjà un candidat existant avec cette adresse mail.
2. si oui, mettre le département de la répartition qui inscrit le candidat
3. Cela suppose que l'ancienne répartition a supprimé le candidat de la liste blanche pour que la nouvelle répartition puisse l'ajouter dans sa liste blanche.
