### ISSUE TITLE
Chargement de places en dehors des horaires autorisés (WARN)

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#642]
#### Case d'usage:
ETR, j'ai fait commis une erreur dans le chargement de places de 8h00 à 18h (12h00  inclus ) pour un inspecteur,  je veux affecter cet inspecteur dans à un autre centre avec les mêmes horaires 

#### Remarques: 
La suppression places sur la journée ne supprime pas les places en dehors des horaires affichés  dans la base de données. Par conséquent, il est impossible de charger des places dans un autre centre pour cet inspecteur pour cette journée.   
Les inspecteurs ayant des places en dehors des horaires ne sont pas visibles

**Comment by baudointran** [comment]
Que doit-on faire?
1. Quand le répartiteur sélectionne la suppression de la journée, les places de la journée sont supprimé
2. Afficher les places hors horaires pour les supprimer ensuite le répartiteur
3. interdire la chargement des places hors horaires autorisé

**Comment by Evbern** [comment]
Attendre le retour de @Fred semaine du 02/09

**Comment by baudointran** [comment]
@Evbern  @fred
Je propose le solution ci-dessous, êtes-vous d'accord?
- [ ] : ETR, je charge les places en dehors de la plage des horaires autorisé, je reçois des messages d'erreurs suivantes: La place n'est pas enregistré, La place est en dehors de la plage horaires autorisés,

Les horaires autorisés sont [  '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00',  '11:30', '13:30', '14:00', '14:30','15:00', '15:30']

**Comment by Evbern** [comment]
@baudointran C'est OK pour nous ! (j'ai légèrement ajusté le texte)
