### ISSUE TITLE
Actualisation auto page d'accueil et page planning

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#646]
ETR, je peux consulter dans l'application des informations relatives au places (ex : nb de places réservées, nb de places disponibles, nb de places indisponibles, ratios, ...). Il convient : 
- [ ] Actualiser automatiquement les données toutes les 10 secondes en page d'accueil
- [ ] Actualiser automatiquement les données toutes les 10 secondes sur la page de gestion du planning

**Comment by baudointran** [comment]
Est-ce que c'est toujours d'actualité?
