### ISSUE TITLE
Conserver, date et heure de la confirmation / modification d'une reservation candidat

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#653]
Conserver, date et heure :

[ ] => pour le Candidat lors de la confirmation d'une réservation ainsi que sa confirmation de modification

[ ] => pour l'Admin lors de l'affectation d'un candidat, le changement d'inspecteur (déplacer date et heure sur la nouvelle place), la suppression (archivage),

**Comment by pli01** [comment]
Validé
