### ISSUE TITLE
Redirection vers la page de connexion pour les token invalides

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#675]
ETC, mon lien n'est plus valide ou ma session n'est plus valide, je souhaite retourner sur la page de connexion (pré-inscription).

Remarque:
   Quand le token n'est plus valide et qu'il est sur la page de selection de places, le candidat un message technique tous les 5 second et les logs sont pollué par 'jwt malforme'

**Comment by Evbern** [comment]
@laruiss @baudointran OK
