### ISSUE TITLE
ETC : voir que les noms des centres sont cliquables

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#685]
ETC quand j'ai accès à la liste des centres, je veux que mon curseur change de forme pour m'indiquer que les noms des centres sont cliquables.

- [x] le curseur prend une forme de lien cliquable lorsque ma souris passe sur les noms des centres d'examen

**Comment by Evbern** [comment]
@laruiss @Carolinedanslesnuages 
C'est OK !
