### ISSUE TITLE
Fenêtre coupé aprés la selection de "annuler reservation"  puis "modifier l'inspecteur"

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#689]
![image](https://user-images.githubusercontent.com/16351036/64532953-cb962e80-d312-11e9-9187-df9ddf78161a.png)

**Comment by Evbern** [comment]
@laruiss @baudointran KO


file:///home/ubuntu/Images/Capture%20du%202019-10-02%2016-20-10.png

**Comment by Evbern** [comment]
@laruiss @baudointran KO

**Comment by Evbern** [comment]
@laruiss @baudointran KO

![image](https://user-images.githubusercontent.com/48919541/66052819-863fd800-e531-11e9-94bb-55264cf3193b.png)

**Comment by Evbern** [comment]
@laruiss @baudointran 
C'est OK !
