### ISSUE TITLE
Journaliser les actions effectuées sur l'application (8)

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#69]
En tant que ops, je dois pouvoir connaître les actions effectuées par les utilisateurs (candidats et admin) sur l'application.

- [x] Faire une première implémentation simple de journalisation des actions des utilisateurs sur l'appli.

- [x] Avoir le retour de pli01 et philippeBron

- [x] Corriger l'implémentation en fonction

**Comment by pli01** [comment]
#161 : premiere implementation de journalisation

**Comment by pli01** [comment]
En complément, les logs nginx des fronts seront formatées en json pour faciliter la recherche/indexation (cf #163 )
Les logs (HTTP apache/style) de l'API pourraient etre aussi formatée en json (sous la clef node pour identifié le process) ?
{ "node": { "request":"GET /api/v2", "status": 304, "request_time": 0.01, ..... }}

**Comment by pli01** [comment]
Correction du format json des front nginx (#180 )

**Comment by laruiss** [comment]
Est-ce qu'on peut fermer ce ticket
