### ISSUE TITLE
ETR: je souhaite ajouter ajouter/supprimer/modifier les IPCSR

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#698]
En tant que répartiteur/délégué, je souhaite gérer la liste de IPCSR.
- [ ] ajouter
- [ ] supprimer
- [ ] modifier
- [ ] importer une liste

Les champs/colonnes nécessaires pour un IPCSR sont:
*  département 
*  nom: (majuscule)
*  prénom: (majuscule)
*  email
*  matricule

**Comment by baudointran** [comment]
Attention:
 - A la suppression, Que doit-on faire s'il y a des places affectés à l'inspecteur et s'il y a une réservation
