### ISSUE TITLE
ETC - Enrichir mails confirmation de réservation

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#713]
Il faudrait ajouter à la fin du mail :

"48h après le passage de votre examen (week-end et jours fériés non inclus) vous avez la possibilité de consulter votre résultat sur https://www.securite-routiere.gouv.fr/resultats-du-permis-de-conduire. En cas de réussite, vous devrez solliciter par vous même la fabrication de votre permis de conduire sur le site de l'ANTS"

Il faudrait que cette information soit lisible et non pas noyée dans la masse d'information... un encadré rouge ou bleu pour attirer l’œil ?

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/65049467-1264d380-d966-11e9-9ebd-13ea70c9de0c.png)

**Comment by jclaudan** [comment]
modifier "En cas de réussite:" par "Résultat de votre examen" vue avec le métier

**Comment by Evbern** [comment]
@baudointran  OK pour le texte, avec un encadré **en bleu**
Merci !

**Comment by Evbern** [comment]
@jclaudan @laruiss @baudointran 
C'est OK
