### ISSUE TITLE
ETC, les liens Github et LGPL ne fonctionnent pas dans "mentions légales"

### ISSUE THREAD

**Issue by Archibald-Perez** [LAB-MI/candilibV2#718]
Les liens contenus dans "Mentions légales" vers github et licenses LGPL se terminent par un point, et ne renvoient donc pas sur la bonne page.
On a :
<https://github.com/LAB-MI/candilib.>
au lieu de :
https://github.com/LAB-MI/candilib

**Comment by Evbern** [comment]
@laruiss KO

**Comment by Evbern** [comment]
@laruiss @Carolinedanslesnuages 
C'est OK
