### ISSUE TITLE
ETR - Disposer dans l'application des KPI Places (5)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#721]
ETR, je souhaite disposer de 2 KPI relatifs à l'utilisation des places dans Candilib, sur la page dédiée au KPI : 
- [x] Affichage du taux de réservation futur (réservations à venir* / places proposées dans le futur)
- [x] Affichage juxtaposé du nombre de candidats inscrits**, du nombre de places proposées dans le futur et du nombre de réservations à venir

*Réservations à venir = somme des places réservées dans le futur (aujourd'hui inclus)
**Candidats inscrits = somme des candidats validés par Aurige

**Comment by baudointran** [comment]
Proposition de maquette en attente de validation:

![image](https://user-images.githubusercontent.com/16351036/66028759-08160e00-e4fe-11e9-99c6-a081d719d8e0.png)

**Comment by baudointran** [comment]
lié à #580

**Comment by jclaudan** [comment]
n'affichant plus les "candidats inscrits" mais les "candidats inscrits sans réservation" je propose de renommé le label @Evbern si tu a un label en particulier je t'invite à l'indiquer ;-)

**Comment by Evbern** [comment]
Quelques points @jclaudan 
- [ ] Le nombre de réservations à venir n'est pas affiché dans le diagramme en barre => L'afficher
- [ ] Le nombre de places disponibles à venir est affiché dans le diagramme => Afficher à la place le nombre de places proposées dans le futur (= nombre de places disponibles + nombre de places réservées)
- [ ] Lorsqu'un candidat réserve une place, il est décompté du nombre de candidats inscrits => Il faut le conserver dans le caclul du nombre de candidats inscrits tant qu'il n'a pas réussi l'examen (il sera alors archivé)
- [ ] Le titre "Places d'examens" est à aligner avec le titre "Résultats des examens"

**Comment by philippeBron** [comment]
Libellés : remplacer
- [ ] "Places disponibles à venir" par "Places disponibles" et
- [ ] "Candidats inscrits" par "Candidats sans réservation"
