### ISSUE TITLE
Utilisateur non reconnu lors de la demande d'un magic link

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#728]
ETC quand je clique sur le bouton "Déjà inscrit ?" pour recevoir un lien de connexion j'ai le message d'erreur "Utilisateur non reconnu" lorsque je saisie mon adresse mail avec une majuscule.

**Comment by Evbern** [comment]
@laruiss  OK

**Comment by Evbern** [comment]
@laruiss OK
