### ISSUE TITLE
e2e: isoler les dependances des plugins cypress

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#779]
Pour réaliser les tests e2e, via cypress, seulement 2 plugins sont necessaires.
Actuellement ils sont décrit à 2 endroits :
* dans le package.json du client, en dependance de prod, 
* et également décrit dans le e2e.Dockerfile servant à la construction du container cypress utilsé dans la chaine de CI/CD

**Comment by laruiss** [comment]
Je n'en vois qu'un : `cypress-file-upload`. Pourquoi a-t-on besoin de l'ajouter dans le e2e.Dockerfile ?

**Comment by pli01** [comment]
> cypress-file-upload

Le 2eme plugin (cypress-mailhog) a été supprimé lors des précédent commit. (surement normal)  .... (https://github.com/LAB-MI/candilibV2/commit/715e8d0ed109441ae6de830f8999d58df2857a51).

Enfin, le container e2e, n'a pas besoin d'installer toutes les dépendances de l'appli issue du package.json, mais seulement du (/des) plugin(s) necessaire au fonctionnement de cypress.  (file-upload, mail)
(voir dans les logs travis le mot clé e2e.Dockerfile pour voir les dependances minimales)

Pas d'autres idées  , que de spécifier le plugin a installer dans la commande npm install du dockerfile e2e, sans tirer toutes les dépendances inutiles.

**Comment by laruiss** [comment]
Note après discussion : il faut réfléchir à embarquer un `package.json` et un `package-lock.json` minimaliste pour le conteneur Cypress.
