### ISSUE TITLE
ETC - Recevoir le mail de confirmation de validation d'adresse mail, sans whitelist (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#801]
ETC, je reçois un mail confirmant la validation de mon adresse mail déclarée lors de mon inscription. Il convient d'apporter les modifications suivantes à ce mail :
- [x] Dans le mail : ajout d'un lien "Contactez-nous" en bas du mail
- [x] Ce lien renvoie vers l'adresse mail du contact départemental, relatif au choix du département du candidat réalisé lors de la pré-inscription

**Comment by jclaudan** [comment]
<p>Madame, Monsieur ${nomMaj},</p>
  <br>
  <p>Vous avez demandé à être inscrit·e sur le site de réservation de l'examen pratique du permis de conduire.</p>
  <br/>
  <p>
  <p>
    Pour poursuivre votre inscription, vous devez valider votre adresse mail en cliquant sur lien ci-après :
  </p>
  <p>
    <a href="${urlValidationEmail}">
      Valider mon adresse courriel
    </a>
  </p>
  <br/>
  <p>
      <b><u>Ce lien est valable 2 heures à compter de la réception de cet email.</u></b>
  </p>
  <p>
    Passé ce délai, vous devrez de nouveau faire une demande de pré-inscription sur <a href="${urlConnexion}">Candilib</a>.
  </p>
  <br/>
<a href="mailto:qwertyuiop@candilib.com"> Contactez-nous </a>

  <p align="right"> L'équipe Candilib </p>

**Comment by Evbern** [comment]
Top @jclaudan

**Comment by laruiss** [comment]
@jclaudan Est-ce que c'est fait, la gestion des départements ?
