### ISSUE TITLE
ETC - Cliquer sur "Déjà inscrit" (sans whitelist)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#803]
ETC, je souhaite me connecter à Candilib. Je clique sur le bouton "Déjà inscrit". Je reçois le mail classique permettant de me connecter avec mon magiclink
- [ ] Dans le mail : ajout d'un bouton "Contactez-nous" en bas du mail qui renvoie vers l'adresse mail du contact départemental

**Comment by laruiss** [comment]
@jclaudan Peut-on fermer ce ticket ?
