### ISSUE TITLE
ETR - Consulter la liste des candidats en attente des 30 jours

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#805]
avoir l'information dans la ficher candidat:

- [x] -savoir si il est en quarantaine ou non
- [x] savoir le nombre de jour restant avant l’accès au réservation 

UX: mettre en évidence  le statue selon une couleur particulière

**Comment by Carolinedanslesnuages** [comment]
@Evbern    'savoir si il est en quarantaine' corresponds à mettre en évidence avec une couleur particulière ou bien à une nouvelle ligne dans la fiche candidat ?

**Comment by Evbern** [comment]
@Carolinedanslesnuages A demander à @jclaudan qui a détaillé cet issue. @jclaudan peux-tu nous éclairer ? Merci !
