### ISSUE TITLE
ETC - Consulter la FAQ (sans whitelist) (1)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#806]
A détailler (ajout contact des départements, suppression du fonctionnement par whitelist)
- modifier wording de la FAQ concernant la mise en quarantaine.

**Comment by JoelPagniez** [comment]
# Proposition de  wording pour la FAQ
_texte pré-existant en italique_

 **_`Qui peut utiliser le service ?`_**
    ~~`Les « candidats libres » qui ont reçu un mail d'invitation pour participer à l'expérimentation.`~~
    `Tout « candidat libre » peut utiliser le service.`

**_`Comment ça marche ?`_**
    ~~`Vous avez reçu une invitation nominative par mail à vous inscrire sur Candilib.`~~
  _`  Pour s'inscrire ...`_

**`Quand pourrais-je accéder au planning de réservation ?`**
         `Après l'acceptation de votre inscription, vous devez attendre 30 jours avant de pouvoir accéder au planning de réservation. Cette mise en file d'attente vous permet de planifier votre préparation en vue de réussir votre examen du permis de conduire.` 

**~~`Je n’ai pas été invité à participer à l’expérimentation ?`~~**
    ~~`Ce service est restreint aux candidats qui ont reçu un mail d'invitation à participer à cette expérimentation.`~~

**_`Aide / Contact`_**
    ~~`Ce service est restreint aux candidats qui ont reçu un mail d'invitation à participer à cette expérimentation.`~~
    ~~`Posez vos questions à l'adresse courriel présente dans votre mail d'invitation`~~
    `Si vous vous êtes déjà pré-inscrit, posez vos questions à l'adresse de contact personnalisé que vous avez reçu par courriel.`
    `Si `~~`vous n'avez pas trouvé de réponse à vos questions dans ces informations`~~`vous n'êtes pas pré-inscrit`_`, vous pouvez nous contacter à cette adresse candilib@interieur.gouv.fr`_

ceci répond aussi de manière générique à l'issue [#880](https://github.com/LAB-MI/candilibV2/issues/880)

**Comment by Evbern** [comment]
@JoelPagniez  OK

**Comment by laruiss** [comment]
Ne faut-il pas lister les départements dans lesquels le service sera ouvert ?
Et donc `Tout « candidat libre » peut utiliser le service. Cependant, seuls les départements de la liste suivante propose des places via ce service :` ?

**Comment by baudointran** [comment]
Réponse sur l'issue #885
