### ISSUE TITLE
ETD - Gérer les délégués/répartiteurs (ajout/suppr)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#814]
ETD, je dois pouvoir gérer les comptes des délégués/répartiteurs comme suit
- [x] Accéder à une page de gestion dédiée pour mon département
- [x] Pouvoir consulter la liste des informations suivantes : email, statut, département
- [x] Ajouter un délégué/répartiteur sur mon département
- [x] Supprimer un délégué/répartiteur sur mon département

**Comment by jclaudan** [comment]
![IMG_20191118_122756](https://user-images.githubusercontent.com/36130708/69048924-f382cc00-09fe-11ea-825b-dfe9d3172845.jpg)
