### ISSUE TITLE
Lors de l'indisponibilité des relais SMTP, Echec de l'envoi des mails sans essai multiple

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#837]
Lors de l'indisponibilité des relais SMTP, l'envoi des mail (synchroAurige, connexion candidat,...)
est en echec.
Les mails ne sont pas délivrés.
Il n'y pas de mutliples tentatives d'envoi.
Pour la synchroAurige, les candidats ne sont pas notifiés.

```
SMTPConnection error
Error: Message failed: 421 4.4.2 XXX.XXX  Error: timeout exceeded
```

**Comment by baudointran** [comment]
Le timeout de nodemail par défaut est de 2 minutes

**Comment by baudointran** [comment]
non reproduit depuis l'ajoute de proxy SMTP en local
