### ISSUE TITLE
modifier le sujet du mail envoyé en cas de succès à l'examen

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#842]
Le sujet du mail envoyé lorsqu'un.e candidat.e réussi l'épreuve pratique est :
"problème inscription candilib".

Il faudrait avoir un titre de mail **identique** pour une réussite pas encore sur le site SR et lorsqu'un candidat est en retour au permis.

- [ ] ETC : recevoir un mail avec le titre suivant "Information Candilib"

**Comment by Evbern** [comment]
OK !

**Comment by Evbern** [comment]
Ok !

**Comment by baudointran** [comment]
même issue que  #594

**Comment by baudointran** [comment]
@Evbern 
Suite à  la discussion avec Fréd en Août, il y a un problématique à l'envoi de mail de réussite.
Le candidat connaît trop tôt son résultat . Le résultat saisie par l'inspecteur peut être erroné et il y a une vérification manuelle des résultats.

Le mieux est de ne pas d'envoyer de mail, mais il faut tout même avertir le candidat lors de connexion qu'il ne peux pas accéder suite à une réussite.
