### ISSUE TITLE
ETC - Consulter la landing page avec wording ajusté

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#852]
Réaliser les ajustements suivants :

- [x] Remplacer les "mail(s)" et "email(s)" par "courriel(s)"
- [x] Ajouter des points "." à l'ensemble des phrases en dessous des titres et lorsqu'on clique sur une étape (pas des titres !)
- [x] Remplacer (étape 1) "Vous remplirez un formulaire en ligne" par "Remplissez le formulaire en ligne"
- [x] Remplacer (étape 2) "Vous validerez" par "Validez"
- [x] Remplacer (étape 4) "Attente de" par "Attendez"
- [x] Remplacer (étape 5) "Connexion à l'application par le magic link" par "Connectez-vous à l'application par le lien"

**Comment by baudointran** [comment]
Voici le résultat :
![image](https://user-images.githubusercontent.com/16351036/77889855-d4c6f880-726e-11ea-9072-86bc8cbd4947.png)
