### ISSUE TITLE
ETD / ETR - Recevoir mail création de compte

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#883]
Modification du mail de création de compte délégué / répartiteur : 

- [x] "Votre compte sur Candilib vient d'être créé. Vous pouvez dès à présent modifier votre mot de passe en cliquant sur le lien suivant : modifier mon mot de passe"

**Comment by Carolinedanslesnuages** [comment]
@Evbern 
![image](https://user-images.githubusercontent.com/45307611/72737496-f7b69b80-3b9f-11ea-8ac8-883a5a270a80.png)

**Comment by Evbern** [comment]
Ok ! merci

**Comment by Evbern** [comment]
Ok !
