### ISSUE TITLE
ETC - Ajouter section département dans la FAQ

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#885]
ETC, je veux consulter la liste des départements de passage à Candilib : 
- [x] Ajouter le contenu suivant : "Candilib n'est accessible qu'aux candidats des départements suivants : 38, 69, 75, 77, 78, 91, 92, 93, 94, 95.
NB : les candidats du 75, du fait des conditions de circulation dans Paris intramuros, pourront choisir parmi les centres d'examen suivants : Rosny Sous Bois, Noisy Le Grand, Saint Leu La Forêt, Gennevilliers, Bobigny, Vélizy-Villacoublay"

**Comment by baudointran** [comment]
TECH:
- [ ] La liste de départements doit provenir de la collection des départements de la base de données
- [ ] La liste des centres du 75 doit provenir de la collection des centres de la base de données

**Comment by JoelPagniez** [comment]
Pour répondre à l'issue #806 je suis parti sur 
**Qui peut utiliser le service ?**
Tout « candidat libre » peut utiliser le service.
Cependant, seuls les départements de la liste suivante proposent des places via ce service : 93, 75
NB : les candidats du 75, du fait des conditions de circulation dans Paris intramuros, pourront choisir parmi les centres d'examen suivants : Rosny sous bois, Saint Leu la Foret, Noisy le Grand

Faut-il eclater cette FAQ en 2 avec la question supplémentaire "Dans quel département puis-je passer l'examen ?"
"Candilib n'est accessible qu'aux candidats des départements : ..." correspond bien à "Qui peut utiliser le service ?"

**Comment by Evbern** [comment]
OK ! @JoelPagniez
