### ISSUE TITLE
ETC : Ne pas être archivé le jour de l'expiration de mon ETG

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#893]
L'ETG est valable 5 ans le jour de l'obtention inclu. ETC je ne dois pas recevoir de mail de résiliation 5 ans après jour pour jour.
- [ ] ETC je suis retiré de Candilib le lendemain de la date anniversaire des 5 ans de l'obtention de l'ETG.

**Comment by baudointran** [comment]
TECH:

dans la fonction de Synchro-aurige, mettre cette date en fin de journée

**Comment by baudointran** [comment]
Avec cette solution, Si le candidat passe son examen le jour de péremption de son code, il sera archivé le lendemain sans le résultat et même si le résultat et connu.

**Comment by baudointran** [comment]
A l'instant du passage de synchro-aurige, on a les cas ci-dessous:

- [ ]  Le candidat n'a pas de réservation et  sa date ETG est périmé aujourd'hui, alors le candidat est archivé par synchro-aurige
- [ ] Le candidat a une réservation qui est dans le future et  sa date ETG est périmé aujourd'hui, , alors le candidat est archivé par **synchro-aurige
- [ ] Le candidat a une réservation qui n'est pas dans le future et  sa date ETG est périmé aujourd'hui et  aurige m'informe qu'il a échoué alors le candidat est archivé par synchro-aurige
- [ ] Le candidat a une réservation qui n'est pas dans le future et  sa date ETG est périmé aujourd'hui et  aurige m'informe qu'il a réussi alors le candidat est archivé par synchro-aurige
- [ ]  Le candidat a une réservation dans le passé et  sa date ETG est périmé aujourd'hui et  aurige n'a pas retourné d'information sur son examen alors le candidat n'est pas archivé

**Comment by baudointran** [comment]
Si le candidat à réserver,  Candilib peut attendre 7 jours de non réponse de résultat d aurige avant d'archiver le candidat

**Comment by laruiss** [comment]
Est-ce que c'est terminé, ça ? Rien n'est coché, pour l'instant, et pourtant ça a été fusionné

**Comment by baudointran** [comment]
Il est terminé.
