### ISSUE TITLE
Bug: 403 en cliquant sur le mail de validation

### ISSUE THREAD

**Issue by raphaelbadia** [LAB-MI/candilibV2#902]
En tant que candidat, lorsque je clique sur le lien dans le mail de validation :
```
Pour poursuivre votre inscription, vous devez valider votre adresse mail en cliquant sur lien ci-après :

Valider mon adresse courriel
```

Je suis redirigé sur /email-validation?e=raphael%40badia.cc&h=ab760877-1199-44db-ab60-9d46d74f8ecb

J'ai une 403 
![image](https://user-images.githubusercontent.com/1901628/71548017-1e6e2180-29a8-11ea-98ee-f3d894d1a625.png)

En remplaçant le .cc de mon mail par .com , là j'arrive à une page d'erreur (normal) 
![image](https://user-images.githubusercontent.com/1901628/71548029-4eb5c000-29a8-11ea-96ae-f3a0ea2cfc37.png)

Il y a une whitelist de tld ?

**Comment by pli01** [comment]
Fixé
