### ISSUE TITLE
ETA : problème lors de la création de répartiteur

### ISSUE THREAD

**Issue by jclaudan** [LAB-MI/candilibV2#904]
sur la page 'LISTE DES RÉPARTITEURS/DÉLÉGUÉS'
- Departement existant '93' et '75'
je crée un répartiteur avec seulement le département '75'
ensuite lorsque j'effectue une nouvelle création la sélection précédente est toujours effective mais si je valide le user est crée avec les départements par default c.a.d '93' et '75'

**Comment by baudointran** [comment]
Non, reproduire avec la version qualif/v2.5.0-rc1.
Après la création d'un utilisateur, les départements sont décochés
