### ISSUE TITLE
ETD : disposer de la première lettre du prénom de l'inspecteur (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#911]
ETD, il est souhaité de pouvoir voir la première lettre du prénom d'un IPCSR sur l'ensemble de l'expérience utilisateur. Par exemple, 2 inspecteurs homonymes vont travailler sur un même centre d'examen. Il convient de pouvoir les distinguer.

- [x] Ajouter la première lettre du prénom dans la fiche de l'IPCSR
- [x] Ajouter la première lettre du prénom dans le planning des examens

**Comment by Carolinedanslesnuages** [comment]
Je ne comprends pas la demande 
Pourquoi disposer de la première lettre puisqu'il y a les prénom complet autant sur la fiche de l'IPCSR que sur le planning d'examen. @Evbern  @laruiss

**Comment by Evbern** [comment]
Ok merci, on met en standby

**Comment by laruiss** [comment]
Fusionné mais aucune case n'est cochée. Est-ce qu'on peut fermer ce ticket ?

**Comment by Carolinedanslesnuages** [comment]
Oui.
