### ISSUE TITLE
ETC - Disposer du mail de contact dans le mail d'attente de vérification

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#944]
ETC, je souhaite
- [x] Du mail de contact dans le mail informant de l'attente liée à la vérification Aurige

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72739108-4a458700-3ba3-11ea-9c46-02995e227b6a.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72739150-647f6500-3ba3-11ea-864b-ef93d88b0077.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72739235-8bd63200-3ba3-11ea-8895-541790e554e0.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72741674-6d266a00-3ba8-11ea-994c-e6099359930e.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72741880-d7d7a580-3ba8-11ea-95da-dd62361a61e2.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/72741977-10777f00-3ba9-11ea-94d3-62fb0374d2d0.png)

**Comment by baudointran** [comment]
@Evbern 
tu trouveras ci-dessus les exemples de e-mails corrigés avec la ligne de contacts

**Comment by Evbern** [comment]
Ok merci. Top
