### ISSUE TITLE
ETC - Consulter le nombre de jours restant dans le mail de fil d'attente

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#945]
Il convient de mettre à jour le mail de mise en file d'attente comme suit :
- [x] Mettre à la ligne et sauter une ligne après la phrase commençant par "A ce jour"
- [x] Mettre en gras et dans une police supérieure le nombre de jours restants
- [x] Mettre en gras la date à partir de laquelle le candidat pourra se connecter

**Comment by baudointran** [comment]
@Evbern 

voici le résultat: 
![image](https://user-images.githubusercontent.com/16351036/72738074-14070800-3ba1-11ea-8f46-d031cb684668.png)

**Comment by Evbern** [comment]
Top !
