### ISSUE TITLE
Annuler une réservation de place

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#98]
ETU je peux annuler ma réservation de place d'examen. Je dois confirmer l'annulation et, avant cela, je dois être prévenu des contraintes (pas de réservation possible avant 45j sauf cas justifié d'annulation).

Lorsque ma réservation est annulée, je dois être prévenu qu'un email de confirmation va m'être envoyé, et cet email doit m'être envoyé.

- [x] Composants front
- [x] Appel API client
- [x] API côté serveur
- [x] Réception réponse API

Dépend de #133 #137 #134

**Comment by laruiss** [comment]
Fait
