### ISSUE TITLE
Erreur log technique: Cast to date failed for value "null" at path "date" for model "Place"

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#985]
Message technique de type "error" de l'API
* remettre en forme le message
* voir la cause et la conséquence associé (peut etre liée à une recherche de place)

```json
{"content":{"default":"Cast to date failed for value \"null\" at path \"date\" for model \"Place\""},"meta":{"level":"error","label":"app","timestamp":"2020-01-28T09:53:29.326Z"}}
```

**Comment by baudointran** [comment]
le message n'est pas réapparu après  la livraison de la  v2.6.0-rc1
